/**
 * param-type-enforcement.test.js — the boundary validator enforces a parameter's DECLARED `type`.
 *
 * THE DEFECT THIS PINS (D-22 root cause): `validateParamsAgainstSchema` checked that a parameter's
 * NAME was declared and that required names were present, and then ignored `properties[k].type`
 * entirely. A schema saying `type:'string'` accepted a number, an array, an object or a boolean.
 * The published contract was advertising a guarantee the door did not keep, so the caller debugged
 * a downstream symptom instead of reading a refusal that named the parameter.
 *
 * DRIVEN OFF THE SCHEMA, NEVER OFF A HAND-LISTED PARAM TABLE. Every case below is generated by
 * WALKING `NATIVE_MCP_TOOLS[].inputSchema.properties`. A hand-mirrored list of "params that should
 * be strings" would be exactly the schema-mirror drift this row exists to eliminate: it would go
 * green while a newly added parameter went unchecked. Adding a tool or a parameter automatically
 * adds its cases here.
 *
 * FIXTURE HONESTY. A gate that cannot fail is not a gate. Every generated refusal case is paired
 * with a CONFORMING value for the same parameter that MUST be accepted — so a validator that
 * simply threw on everything would fail this suite rather than pass it.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
    NATIVE_MCP_TOOLS,
    SCHEMA_TYPE_PREDICATES,
    SUPPORTED_SCHEMA_TYPES,
    declaredTypesOf,
    runtimeTypeOf,
    valueMatchesDeclaredType,
    validateParamsAgainstSchema,
} from '../src/mcp-tools/index.js';

/** One conforming specimen per supported type word — the source of every "must be accepted" case. */
const SPECIMEN = {
    string: 'a-string',
    number: 3.5,
    integer: 7,
    boolean: true,
    array: ['x'],
    object: { k: 'v' },
    null: null,
};

/** A value that conforms to `types`, or undefined when we cannot build one. */
function conformingValue(types) {
    for (const t of types) if (t in SPECIMEN && t !== 'null') return SPECIMEN[t];
    return undefined;
}

/** A value whose runtime type is in NO declared type of `types` — the refusal specimen. */
function violatingValue(types) {
    const declared = new Set(types);
    for (const t of ['string', 'number', 'boolean', 'array', 'object']) {
        if (declared.has(t)) continue;
        // `integer` is satisfied by a number specimen, so a number cannot violate `number|integer`.
        if (t === 'number' && (declared.has('integer') || declared.has('number'))) continue;
        if (t === 'object' && declared.has('object')) continue;
        return SPECIMEN[t];
    }
    return undefined;
}

/** Every (tool, param) pair the SSOT declares — walked, never listed. */
function declaredParams() {
    const out = [];
    for (const tool of NATIVE_MCP_TOOLS) {
        const props = tool.inputSchema?.properties;
        if (!props || typeof props !== 'object') continue;
        for (const [name, def] of Object.entries(props)) out.push({ tool, name, def });
    }
    return out;
}

/** Minimum accepted bag for a tool: every required param filled with a CONFORMING specimen. */
function baseBag(tool) {
    const props = tool.inputSchema?.properties || {};
    const bag = {};
    for (const r of tool.inputSchema?.required || []) {
        const v = conformingValue(declaredTypesOf(props[r]));
        if (v !== undefined) bag[r] = v;
    }
    return bag;
}

test('every declared type word across the SSOT is one the validator can actually enforce', () => {
    const params = declaredParams();
    assert.ok(params.length > 0, 'fixture check: the SSOT must declare parameters to walk');
    const unenforceable = [];
    for (const { tool, name, def } of params) {
        for (const word of declaredTypesOf(def)) {
            if (!SUPPORTED_SCHEMA_TYPES.includes(word)) unenforceable.push(`${tool.name}.${name} -> '${word}'`);
        }
    }
    assert.deepEqual(unenforceable, [],
        'a type word the validator does not know is advertised but NOT enforced — it must be added to '
        + `SCHEMA_TYPE_PREDICATES or corrected in the schema. Supported: ${SUPPORTED_SCHEMA_TYPES.join(', ')}`);
});

test('every declared parameter carries a type — an untyped param is unenforceable by construction', () => {
    const untyped = declaredParams()
        .filter(({ def }) => declaredTypesOf(def).length === 0)
        .map(({ tool, name }) => `${tool.name}.${name}`);
    assert.deepEqual(untyped, [], 'these params publish no `type`, so the boundary cannot enforce one');
});

test('a schema `default` and every `enum` member conform to that parameter\'s own declared type', () => {
    const selfContradictory = [];
    for (const { tool, name, def } of declaredParams()) {
        if ('default' in def && def.default !== null && def.default !== undefined && !valueMatchesDeclaredType(def.default, def)) {
            selfContradictory.push(`${tool.name}.${name} default is ${runtimeTypeOf(def.default)}, declared '${declaredTypesOf(def).join('|')}'`);
        }
        for (const e of Array.isArray(def.enum) ? def.enum : []) {
            if (!valueMatchesDeclaredType(e, def)) {
                selfContradictory.push(`${tool.name}.${name} enum member is ${runtimeTypeOf(e)}, declared '${declaredTypesOf(def).join('|')}'`);
            }
        }
    }
    assert.deepEqual(selfContradictory, [], 'a schema that contradicts itself would now refuse its own advertised value');
});

test('SCHEMA-DRIVEN: a value contradicting the declared type is REFUSED, naming param, declared type and what arrived', () => {
    let cases = 0;
    for (const { tool, name, def } of declaredParams()) {
        const types = declaredTypesOf(def);
        const bad = violatingValue(types);
        if (bad === undefined) continue;
        const bag = { ...baseBag(tool), [name]: bad };
        cases++;
        let err = null;
        try {
            validateParamsAgainstSchema(tool.inputSchema, bag, { commandName: tool.name, surface: 'MCP tools/call' });
        } catch (e) { err = e; }
        assert.ok(err, `${tool.name}.${name}: declared '${types.join('|')}' but ${runtimeTypeOf(bad)} was ACCEPTED`);
        assert.equal(err.code, 'INVALID_PARAMS', `${tool.name}.${name}: wrong error code`);
        // Self-describing: the refusal must name the offender, the declared type and what arrived.
        assert.match(err.message, new RegExp(`'${name}'`), `${tool.name}.${name}: refusal does not name the parameter`);
        assert.match(err.message, /declared type/, `${tool.name}.${name}: refusal does not state the declared type`);
        assert.match(err.message, new RegExp(runtimeTypeOf(bad)), `${tool.name}.${name}: refusal does not state what was received`);
        assert.match(err.message, /NOT coerced/, `${tool.name}.${name}: refusal does not state that no coercion happened`);
        const offenders = (err.data?.mistyped_parameters || []).map(m => m.parameter);
        assert.ok(offenders.includes(name), `${tool.name}.${name}: structured err.data does not carry the offender`);
    }
    assert.ok(cases >= 50, `fixture check: expected the SSOT walk to generate many cases, got ${cases}`);
});

test('FIXTURE CHECK (negative control): the SAME parameters are ACCEPTED when sent as their declared type', () => {
    let cases = 0;
    for (const { tool, name, def } of declaredParams()) {
        const types = declaredTypesOf(def);
        const good = conformingValue(types);
        if (good === undefined) continue;
        const bag = { ...baseBag(tool), [name]: good };
        cases++;
        assert.doesNotThrow(
            () => validateParamsAgainstSchema(tool.inputSchema, bag, { commandName: tool.name, surface: 'MCP tools/call' }),
            `${tool.name}.${name}: a CONFORMING ${types.join('|')} was refused — the gate rejects everything, so its `
            + 'refusals prove nothing',
        );
    }
    assert.ok(cases >= 50, `fixture check: expected many conforming cases, got ${cases}`);
});

test('absence is absence: an omitted or null OPTIONAL parameter is not a type error', () => {
    const tool = NATIVE_MCP_TOOLS.find(t => t.name === 'ask_question_to_app');
    const optional = Object.keys(tool.inputSchema.properties)
        .filter(k => !(tool.inputSchema.required || []).includes(k));
    assert.ok(optional.length > 0, 'fixture check: ask_question_to_app must have optional params');
    for (const k of optional) {
        assert.doesNotThrow(
            () => validateParamsAgainstSchema(tool.inputSchema, { ...baseBag(tool), [k]: null }, { commandName: tool.name }),
            `explicit null on optional '${k}' must read as absent, matching the required check's own definition`,
        );
    }
});

test('a required parameter that is absent is reported as MISSING, not as a type error', () => {
    const tool = NATIVE_MCP_TOOLS.find(t => t.name === 'ask_question_to_app');
    assert.throws(
        () => validateParamsAgainstSchema(tool.inputSchema, { app_id: 'unk-beast' }, { commandName: 'ask_question_to_app' }),
        (e) => e.code === 'INVALID_PARAMS' && /missing required parameter/.test(e.message) && !/wrong parameter type/.test(e.message),
    );
});

test('integer is enforced as distinct from number', () => {
    const schema = { type: 'object', properties: { n: { type: 'number' }, i: { type: 'integer' } } };
    assert.doesNotThrow(() => validateParamsAgainstSchema(schema, { n: 1.5, i: 2 }, { commandName: 'x' }));
    assert.throws(() => validateParamsAgainstSchema(schema, { i: 1.5 }, { commandName: 'x' }),
        (e) => e.code === 'INVALID_PARAMS' && /'i' is declared type 'integer'/.test(e.message));
});

test('a UNION type accepts every member and still refuses a non-member', () => {
    const schema = { type: 'object', properties: { u: { type: ['string', 'number'] } } };
    assert.doesNotThrow(() => validateParamsAgainstSchema(schema, { u: 'a' }, { commandName: 'x' }));
    assert.doesNotThrow(() => validateParamsAgainstSchema(schema, { u: 5 }, { commandName: 'x' }));
    assert.throws(() => validateParamsAgainstSchema(schema, { u: true }, { commandName: 'x' }),
        (e) => /'u' is declared type 'string \| number' but received boolean/.test(e.message));
});

test('NaN and Infinity are not accepted as `number` — a non-finite value is not a quantity', () => {
    const schema = { type: 'object', properties: { n: { type: 'number' } } };
    for (const v of [NaN, Infinity, -Infinity]) {
        assert.throws(() => validateParamsAgainstSchema(schema, { n: v }, { commandName: 'x' }),
            (e) => e.code === 'INVALID_PARAMS', `non-finite ${v} was accepted as a number`);
    }
});

test('a type word the validator cannot enforce makes NO claim rather than a false one', () => {
    // "cannot validate" must never silently mean "reject": an unknown word is caught by the
    // conformance test above, not by refusing a live call.
    const schema = { type: 'object', properties: { x: { type: 'geo-point' } } };
    assert.doesNotThrow(() => validateParamsAgainstSchema(schema, { x: 12345 }, { commandName: 'x' }));
    assert.ok(!SUPPORTED_SCHEMA_TYPES.includes('geo-point'));
});

test('the predicate table is the ONE owner of what each type word means', () => {
    assert.deepEqual(Object.keys(SCHEMA_TYPE_PREDICATES), SUPPORTED_SCHEMA_TYPES,
        'SUPPORTED_SCHEMA_TYPES must be derived from the predicate table, never hand-listed beside it');
    assert.equal(SCHEMA_TYPE_PREDICATES.object(null), false, 'null is not an object on this boundary');
    assert.equal(SCHEMA_TYPE_PREDICATES.object([]), false, 'an array is not an object on this boundary');
    assert.equal(SCHEMA_TYPE_PREDICATES.array([]), true);
});

test('a refusal describes the SHAPE of what arrived and never echoes the value', () => {
    // Declared-string params are exactly the ones that carry secrets in the registered manifests
    // (seat_token, signature, walletSignature, invite_token), and a validation error is a string
    // that gets logged, relayed and pasted into agent context. The refusal must stay diagnostic
    // without becoming an exfiltration path.
    const SECRET = 'sk-live-SUPERSECRET-abcdef0123456789';
    const schema = { type: 'object', properties: { seat_token: { type: 'string' }, limit: { type: 'number' } } };
    for (const bag of [{ seat_token: [SECRET] }, { seat_token: { t: SECRET } }, { limit: SECRET }]) {
        let err = null;
        try { validateParamsAgainstSchema(schema, bag, { commandName: 'probe' }); } catch (e) { err = e; }
        assert.ok(err, `a mistyped value must be refused: ${JSON.stringify(Object.keys(bag))}`);
        assert.ok(!err.message.includes(SECRET), 'the refusal MESSAGE echoed the rejected value');
        assert.ok(!JSON.stringify(err.data).includes(SECRET), 'the refusal DATA echoed the rejected value');
        // still diagnostic: it names the declared type and what arrived
        assert.match(err.message, /declared type/);
    }
    // The shape hint is present and useful for the "3" vs 3 confusion this error exists to resolve.
    try { validateParamsAgainstSchema(schema, { limit: '10' }, { commandName: 'probe' }); assert.fail('not refused'); }
    catch (e) { assert.match(e.message, /received string \(length 2\)/); }
});
