/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { GetAddressStatisticsUTXOs400Response } from '../model/getAddressStatisticsUTXOs400Response';
import { GetAddressStatisticsUTXOs401Response } from '../model/getAddressStatisticsUTXOs401Response';
import { GetAddressStatisticsUTXOs403Response } from '../model/getAddressStatisticsUTXOs403Response';
import { GetAddressStatisticsUTXOsR } from '../model/getAddressStatisticsUTXOsR';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistorical400Response } from '../model/listConfirmedTransactionsByAddressByTimestampUTXOHistorical400Response';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistorical401Response } from '../model/listConfirmedTransactionsByAddressByTimestampUTXOHistorical401Response';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistorical403Response } from '../model/listConfirmedTransactionsByAddressByTimestampUTXOHistorical403Response';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalR } from '../model/listConfirmedTransactionsByAddressByTimestampUTXOHistoricalR';
import { ListConfirmedTransactionsByAddressFromTimestampEVMHistory405Response } from '../model/listConfirmedTransactionsByAddressFromTimestampEVMHistory405Response';
import { ListConfirmedTransactionsByAddressUTXOHistorical400Response } from '../model/listConfirmedTransactionsByAddressUTXOHistorical400Response';
import { ListConfirmedTransactionsByAddressUTXOHistorical401Response } from '../model/listConfirmedTransactionsByAddressUTXOHistorical401Response';
import { ListConfirmedTransactionsByAddressUTXOHistorical403Response } from '../model/listConfirmedTransactionsByAddressUTXOHistorical403Response';
import { ListConfirmedTransactionsByAddressUTXOHistoricalR } from '../model/listConfirmedTransactionsByAddressUTXOHistoricalR';
import { ListUnspentTransactionOutputsByAddressUTXOs400Response } from '../model/listUnspentTransactionOutputsByAddressUTXOs400Response';
import { ListUnspentTransactionOutputsByAddressUTXOs401Response } from '../model/listUnspentTransactionOutputsByAddressUTXOs401Response';
import { ListUnspentTransactionOutputsByAddressUTXOs403Response } from '../model/listUnspentTransactionOutputsByAddressUTXOs403Response';
import { ListUnspentTransactionOutputsByAddressUTXOsR } from '../model/listUnspentTransactionOutputsByAddressUTXOsR';
import { VerifyAddress402Response } from '../model/verifyAddress402Response';
import { VerifyAddress409Response } from '../model/verifyAddress409Response';
import { VerifyAddress415Response } from '../model/verifyAddress415Response';
import { VerifyAddress422Response } from '../model/verifyAddress422Response';
import { VerifyAddress429Response } from '../model/verifyAddress429Response';
import { VerifyAddress500Response } from '../model/verifyAddress500Response';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://rest.cryptoapis.io';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum AddressHistoryUTXOsApiApiKeys {
    ApiKey,
}

export class AddressHistoryUTXOsApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKey': new ApiKeyAuth('header', 'x-api-key'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: AddressHistoryUTXOsApiApiKeys, value: string) {
        (this.authentications as any)[AddressHistoryUTXOsApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Through this endpoint the customer can receive the number of confirmed transactions of a given address based on confirmed/synced blocks only. In the case where there are any incoming or outgoing unconfirmed transactions for the specific address, they will not be counted or calculated here. Applies only for coins.    {warning}To use any endpoint that returns **historical data by address**, the address must first be indexed via the **Manage Addresses → Sync Address** endpoint. Until the address has been synced, requests to historical-data-by-address endpoints will not return data for it. Please ensure each address you intend to query is synced before calling these endpoints.{/warning}
     * @summary Get Address Statistics UTXOs
     * @param blockchain Represents the specific blockchain protocol name, e.g. Bitcoin, Bitcoin Cash.
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while \&quot;testnet\&quot; is test network.
     * @param address Represents the public address, which is a compressed and shortened form of a public key.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     */
    public async getAddressStatisticsUTXOs (blockchain: 'bitcoin' | 'bitcoin-cash', network: 'testnet' | 'mainnet', address: string, context?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: GetAddressStatisticsUTXOsR;  }> {
        const localVarPath = this.basePath + '/addresses-historical/utxo/{blockchain}/{network}/{address}/statistics'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)))
            .replace('{address}', encodeURIComponent(String(address)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling getAddressStatisticsUTXOs.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling getAddressStatisticsUTXOs.');
        }

        // verify required parameter 'address' is not null or undefined
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling getAddressStatisticsUTXOs.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: GetAddressStatisticsUTXOsR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "GetAddressStatisticsUTXOsR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This endpoint will list transactions by an attribute `address`. The transactions listed will detail additional information such as hash, height, time of creation in Unix timestamp, etc.    {warning}To use any endpoint that returns **historical data by address**, the address must first be indexed via the **Manage Addresses → Sync Address** endpoint. Until the address has been synced, requests to historical-data-by-address endpoints will not return data for it. Please ensure each address you intend to query is synced before calling these endpoints.{/warning}
     * @summary List Confirmed Transactions By Address By Timestamp UTXO Historical
     * @param blockchain Represents the specific blockchain protocol name, e.g. Bitcoin, Bitcoin Cash.
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is test network.
     * @param address Represents the public address, which is a compressed and shortened form of a public key.
     * @param timestamp Numeric representation of the starting unix timestamp in seconds since epoch
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param limit Defines how many items should be returned in the response per page basis.
     * @param sortingOrder Defines the sorting order of the results. DESCENDING or ASCENDING by timestamp
     * @param startingAfter Defines the id of the previous listed record id from which the current list should start from.
     */
    public async listConfirmedTransactionsByAddressByTimestampUTXOHistorical (blockchain: 'bitcoin' | 'bitcoin-cash', network: 'mainnet' | 'testnet', address: string, timestamp: number, context?: string, limit?: number, sortingOrder?: string, startingAfter?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalR;  }> {
        const localVarPath = this.basePath + '/addresses-historical/utxo/{blockchain}/{network}/{address}/transactions/from-timestamp/{timestamp}'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)))
            .replace('{address}', encodeURIComponent(String(address)))
            .replace('{timestamp}', encodeURIComponent(String(timestamp)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling listConfirmedTransactionsByAddressByTimestampUTXOHistorical.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling listConfirmedTransactionsByAddressByTimestampUTXOHistorical.');
        }

        // verify required parameter 'address' is not null or undefined
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling listConfirmedTransactionsByAddressByTimestampUTXOHistorical.');
        }

        // verify required parameter 'timestamp' is not null or undefined
        if (timestamp === null || timestamp === undefined) {
            throw new Error('Required parameter timestamp was null or undefined when calling listConfirmedTransactionsByAddressByTimestampUTXOHistorical.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        if (limit !== undefined) {
            localVarQueryParameters['limit'] = ObjectSerializer.serialize(limit, "number");
        }

        if (sortingOrder !== undefined) {
            localVarQueryParameters['sortingOrder'] = ObjectSerializer.serialize(sortingOrder, "string");
        }

        if (startingAfter !== undefined) {
            localVarQueryParameters['startingAfter'] = ObjectSerializer.serialize(startingAfter, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This endpoint will list transactions by an attribute `address`. The transactions listed will detail additional information such as hash, height, time of creation in Unix timestamp, etc.    {warning}To use any endpoint that returns **historical data by address**, the address must first be indexed via the **Manage Addresses → Sync Address** endpoint. Until the address has been synced, requests to historical-data-by-address endpoints will not return data for it. Please ensure each address you intend to query is synced before calling these endpoints.{/warning}
     * @summary List Confirmed Transactions By Address UTXO Historical
     * @param blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc.
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;, \&quot;sepolia\&quot; are test networks.
     * @param address Represents the public address, which is a compressed and shortened form of a public key.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param limit Defines how many items should be returned in the response per page basis.
     * @param startingAfter Defines the id of the previous listed record id from which the current list should start from.
     * @param sortingOrder 
     */
    public async listConfirmedTransactionsByAddressUTXOHistorical (blockchain: 'bitcoin' | 'zcash' | 'bitcoin-cash' | 'litecoin' | 'dogecoin' | 'dash', network: 'mainnet' | 'testnet', address: string, context?: string, limit?: number, startingAfter?: string, sortingOrder?: 'ascending' | 'descending', options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ListConfirmedTransactionsByAddressUTXOHistoricalR;  }> {
        const localVarPath = this.basePath + '/addresses-historical/utxo/{blockchain}/{network}/{address}/transactions'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)))
            .replace('{address}', encodeURIComponent(String(address)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling listConfirmedTransactionsByAddressUTXOHistorical.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling listConfirmedTransactionsByAddressUTXOHistorical.');
        }

        // verify required parameter 'address' is not null or undefined
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling listConfirmedTransactionsByAddressUTXOHistorical.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        if (limit !== undefined) {
            localVarQueryParameters['limit'] = ObjectSerializer.serialize(limit, "number");
        }

        if (startingAfter !== undefined) {
            localVarQueryParameters['startingAfter'] = ObjectSerializer.serialize(startingAfter, "string");
        }

        if (sortingOrder !== undefined) {
            localVarQueryParameters['sortingOrder'] = ObjectSerializer.serialize(sortingOrder, "'ascending' | 'descending'");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ListConfirmedTransactionsByAddressUTXOHistoricalR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ListConfirmedTransactionsByAddressUTXOHistoricalR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Through this endpoint customers can list their transactions\' unspent outputs by `address`.    {warning}To use any endpoint that returns **historical data by address**, the address must first be indexed via the **Manage Addresses → Sync Address** endpoint. Until the address has been synced, requests to historical-data-by-address endpoints will not return data for it. Please ensure each address you intend to query is synced before calling these endpoints.{/warning}
     * @summary List Unspent Transaction Outputs By Address UTXOs
     * @param blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc.
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network.
     * @param address Represents the address that has unspend funds per which the result is returned.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param limit Defines how many items should be returned in the response per page basis.
     * @param offset The starting index of the response items, i.e. where the response should start listing the returned items.
     */
    public async listUnspentTransactionOutputsByAddressUTXOs (blockchain: 'bitcoin' | 'bitcoin-cash' | 'litecoin' | 'dash' | 'dogecoin' | 'zcash', network: 'testnet' | 'mainnet', address: string, context?: string, limit?: number, offset?: number, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ListUnspentTransactionOutputsByAddressUTXOsR;  }> {
        const localVarPath = this.basePath + '/addresses-historical/utxo/{blockchain}/{network}/{address}/unspent-outputs'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)))
            .replace('{address}', encodeURIComponent(String(address)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling listUnspentTransactionOutputsByAddressUTXOs.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling listUnspentTransactionOutputsByAddressUTXOs.');
        }

        // verify required parameter 'address' is not null or undefined
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling listUnspentTransactionOutputsByAddressUTXOs.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        if (limit !== undefined) {
            localVarQueryParameters['limit'] = ObjectSerializer.serialize(limit, "number");
        }

        if (offset !== undefined) {
            localVarQueryParameters['offset'] = ObjectSerializer.serialize(offset, "number");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ListUnspentTransactionOutputsByAddressUTXOsR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ListUnspentTransactionOutputsByAddressUTXOsR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
