/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { ActivateSyncedAddress400Response } from '../model/activateSyncedAddress400Response';
import { ActivateSyncedAddress401Response } from '../model/activateSyncedAddress401Response';
import { ActivateSyncedAddress403Response } from '../model/activateSyncedAddress403Response';
import { ActivateSyncedAddress409Response } from '../model/activateSyncedAddress409Response';
import { ActivateSyncedAddressR } from '../model/activateSyncedAddressR';
import { ActivateSyncedAddressRB } from '../model/activateSyncedAddressRB';
import { GetBlockchainEventSubscriptionDetailsByReferenceID404Response } from '../model/getBlockchainEventSubscriptionDetailsByReferenceID404Response';
import { ListSyncedAddresses400Response } from '../model/listSyncedAddresses400Response';
import { ListSyncedAddresses401Response } from '../model/listSyncedAddresses401Response';
import { ListSyncedAddresses403Response } from '../model/listSyncedAddresses403Response';
import { ListSyncedAddressesR } from '../model/listSyncedAddressesR';
import { SyncAddress400Response } from '../model/syncAddress400Response';
import { SyncAddress401Response } from '../model/syncAddress401Response';
import { SyncAddress403Response } from '../model/syncAddress403Response';
import { SyncAddress409Response } from '../model/syncAddress409Response';
import { SyncAddressR } from '../model/syncAddressR';
import { SyncAddressRB } from '../model/syncAddressRB';
import { VerifyAddress402Response } from '../model/verifyAddress402Response';
import { VerifyAddress409Response } from '../model/verifyAddress409Response';
import { VerifyAddress415Response } from '../model/verifyAddress415Response';
import { VerifyAddress422Response } from '../model/verifyAddress422Response';
import { VerifyAddress429Response } from '../model/verifyAddress429Response';
import { VerifyAddress500Response } from '../model/verifyAddress500Response';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://rest.cryptoapis.io';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum AddressHistoryApiApiKeys {
    ApiKey,
}

export class AddressHistoryApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKey': new ApiKeyAuth('header', 'x-api-key'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: AddressHistoryApiApiKeys, value: string) {
        (this.authentications as any)[AddressHistoryApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Through this endpoint, users can activate a previously synced address with Crypto APIs. Once activated, the address will resume tracking, and any new or missing data associated with it will be synchronized and made available for further operations.
     * @summary Activate Synced Address
     * @param address Represents the public address, which is a compressed and shortened form of a public key.
     * @param blockchain Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc.
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param activateSyncedAddressRB 
     */
    public async activateSyncedAddress (address: string, blockchain: 'polygon' | 'ethereum' | 'dash' | 'tron' | 'dogecoin' | 'litecoin' | 'zcash' | 'bitcoin-cash' | 'bitcoin' | 'ethereum-classic' | 'binance-smart-chain', network: 'mainnet' | 'sepolia' | 'mumbai' | 'amoy' | 'testnet' | 'nile' | 'mordor', context?: string, activateSyncedAddressRB?: ActivateSyncedAddressRB, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ActivateSyncedAddressR;  }> {
        const localVarPath = this.basePath + '/addresses-historical/manage/{blockchain}/{network}/{address}/activate'
            .replace('{address}', encodeURIComponent(String(address)))
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'address' is not null or undefined
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling activateSyncedAddress.');
        }

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling activateSyncedAddress.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling activateSyncedAddress.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(activateSyncedAddressRB, "ActivateSyncedAddressRB")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ActivateSyncedAddressR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ActivateSyncedAddressR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Through this endpoint, users can retrieve a comprehensive list of all addresses synced with Crypto APIs, including their synchronization status and any associated data available for tracking and operations.
     * @summary List Synced Addresses
     * @param blockchain 
     * @param network 
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param limit Defines how many items should be returned in the response per page basis.
     * @param startingAfter Defines the id of the previous listed record id from which the current list should start from.
     */
    public async listSyncedAddresses (blockchain: 'polygon' | 'ethereum' | 'dash' | 'tron' | 'dogecoin' | 'litecoin' | 'zcash' | 'bitcoin-cash' | 'bitcoin' | 'ethereum-classic' | 'binance-smart-chain', network: 'mainnet' | 'sepolia' | 'amoy' | 'testnet' | 'nile' | 'mordor', context?: string, limit?: number, startingAfter?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ListSyncedAddressesR;  }> {
        const localVarPath = this.basePath + '/addresses-historical/manage/{blockchain}/{network}'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling listSyncedAddresses.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling listSyncedAddresses.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        if (limit !== undefined) {
            localVarQueryParameters['limit'] = ObjectSerializer.serialize(limit, "number");
        }

        if (startingAfter !== undefined) {
            localVarQueryParameters['startingAfter'] = ObjectSerializer.serialize(startingAfter, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ListSyncedAddressesR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ListSyncedAddressesR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Through this endpoint, users can synchronize a specific address with Crypto APIs. Once the synchronization is complete, users will have access to the full historical data associated with the address.    {warning}Any address sent for syncing will lead to additional credits consumption on daily bases! Please, refer to **Data Flow Limiting** in the **General Information** section for details.{/warning}
     * @summary Sync Address
     * @param blockchain 
     * @param network 
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param syncAddressRB 
     */
    public async syncAddress (blockchain: 'polygon' | 'ethereum' | 'dash' | 'tron' | 'dogecoin' | 'litecoin' | 'zcash' | 'bitcoin-cash' | 'bitcoin' | 'ethereum-classic' | 'binance-smart-chain', network: 'mainnet' | 'sepolia' | 'amoy' | 'testnet' | 'nile' | 'mordor', context?: string, syncAddressRB?: SyncAddressRB, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: SyncAddressR;  }> {
        const localVarPath = this.basePath + '/addresses-historical/manage/{blockchain}/{network}'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling syncAddress.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling syncAddress.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(syncAddressRB, "SyncAddressRB")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: SyncAddressR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "SyncAddressR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
