/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { GetAddressBalanceSolana400Response } from '../model/getAddressBalanceSolana400Response';
import { GetAddressBalanceSolana401Response } from '../model/getAddressBalanceSolana401Response';
import { GetAddressBalanceSolana403Response } from '../model/getAddressBalanceSolana403Response';
import { GetAddressBalanceSolanaR } from '../model/getAddressBalanceSolanaR';
import { ListTokensByAddressSolana400Response } from '../model/listTokensByAddressSolana400Response';
import { ListTokensByAddressSolana401Response } from '../model/listTokensByAddressSolana401Response';
import { ListTokensByAddressSolana403Response } from '../model/listTokensByAddressSolana403Response';
import { ListTokensByAddressSolanaR } from '../model/listTokensByAddressSolanaR';
import { ListTransactionsByAddressSolana400Response } from '../model/listTransactionsByAddressSolana400Response';
import { ListTransactionsByAddressSolana401Response } from '../model/listTransactionsByAddressSolana401Response';
import { ListTransactionsByAddressSolana403Response } from '../model/listTransactionsByAddressSolana403Response';
import { ListTransactionsByAddressSolanaR } from '../model/listTransactionsByAddressSolanaR';
import { VerifyAddress402Response } from '../model/verifyAddress402Response';
import { VerifyAddress409Response } from '../model/verifyAddress409Response';
import { VerifyAddress415Response } from '../model/verifyAddress415Response';
import { VerifyAddress422Response } from '../model/verifyAddress422Response';
import { VerifyAddress429Response } from '../model/verifyAddress429Response';
import { VerifyAddress500Response } from '../model/verifyAddress500Response';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://rest.cryptoapis.io';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum AddressLatestSolanaApiApiKeys {
    ApiKey,
}

export class AddressLatestSolanaApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKey': new ApiKeyAuth('header', 'x-api-key'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: AddressLatestSolanaApiApiKeys, value: string) {
        (this.authentications as any)[AddressLatestSolanaApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Through this endpoint the customer can receive the balance of a given address based on confirmed/synced blocks only. In the case where there are any incoming or outgoing unconfirmed transactions for the specific address, they will not be counted or calculated here. Applies only for coins.
     * @summary Get Address Balance Solana
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software
     * @param address Represents the public address, which is a compressed and shortened form of a public key.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     */
    public async getAddressBalanceSolana (network: 'mainnet' | 'devnet', address: string, context?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: GetAddressBalanceSolanaR;  }> {
        const localVarPath = this.basePath + '/addresses-latest/solana/{network}/{address}/balance'
            .replace('{network}', encodeURIComponent(String(network)))
            .replace('{address}', encodeURIComponent(String(address)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling getAddressBalanceSolana.');
        }

        // verify required parameter 'address' is not null or undefined
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling getAddressBalanceSolana.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: GetAddressBalanceSolanaR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "GetAddressBalanceSolanaR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Through this endpoint customers can obtain token data by providing an attribute - address. The information that can be returned can include the contract address, the token symbol, type and balance.    {note}Please be advised that retrieving Solana (beta) data will provide you with the most recent day of transactions. For access to full historical data, kindly reach out to our support team.{/note}
     * @summary List Tokens By Address Solana
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software.
     * @param address Represents the public address, which is a compressed and shortened form of a public key.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     */
    public async listTokensByAddressSolana (network: 'mainnet' | 'devnet', address: string, context?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ListTokensByAddressSolanaR;  }> {
        const localVarPath = this.basePath + '/addresses-latest/solana/{network}/addresses/{address}/tokens'
            .replace('{network}', encodeURIComponent(String(network)))
            .replace('{address}', encodeURIComponent(String(address)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling listTokensByAddressSolana.');
        }

        // verify required parameter 'address' is not null or undefined
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling listTokensByAddressSolana.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ListTokensByAddressSolanaR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ListTokensByAddressSolanaR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This endpoint will list transactions by an attribute address. The transactions listed will detail additional information such as hash, height, time of creation in Unix timestamp, etc.    {note}Please be advised that retrieving Solana data will provide you with the most recent day of transactions. For access to full historical data, kindly reach out to our support team.{/note}
     * @summary List Transactions By Address Solana
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software.
     * @param address Represents the public address, which is a compressed and shortened form of a public key.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param limit Defines how many items should be returned in the response per page basis.
     * @param startingAfter String representation of the transaction signature to start searching backwards from. If not provided the search starts from the top of the highest max confirmed block
     */
    public async listTransactionsByAddressSolana (network: 'mainnet' | 'devnet', address: string, context?: string, limit?: string, startingAfter?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ListTransactionsByAddressSolanaR;  }> {
        const localVarPath = this.basePath + '/addresses-latest/solana/{network}/{address}/transactions'
            .replace('{network}', encodeURIComponent(String(network)))
            .replace('{address}', encodeURIComponent(String(address)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling listTransactionsByAddressSolana.');
        }

        // verify required parameter 'address' is not null or undefined
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling listTransactionsByAddressSolana.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        if (limit !== undefined) {
            localVarQueryParameters['limit'] = ObjectSerializer.serialize(limit, "string");
        }

        if (startingAfter !== undefined) {
            localVarQueryParameters['startingAfter'] = ObjectSerializer.serialize(startingAfter, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ListTransactionsByAddressSolanaR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ListTransactionsByAddressSolanaR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
