export * from './aMLApi';
import { AMLApi } from './aMLApi';
export * from './addressAMLApi';
import { AddressAMLApi } from './addressAMLApi';
export * from './addressHistoryApi';
import { AddressHistoryApi } from './addressHistoryApi';
export * from './addressHistoryEVMApi';
import { AddressHistoryEVMApi } from './addressHistoryEVMApi';
export * from './addressHistoryUTXOsApi';
import { AddressHistoryUTXOsApi } from './addressHistoryUTXOsApi';
export * from './addressLatestEVMApi';
import { AddressLatestEVMApi } from './addressLatestEVMApi';
export * from './addressLatestKaspaApi';
import { AddressLatestKaspaApi } from './addressLatestKaspaApi';
export * from './addressLatestSolanaApi';
import { AddressLatestSolanaApi } from './addressLatestSolanaApi';
export * from './addressLatestUTXOsApi';
import { AddressLatestUTXOsApi } from './addressLatestUTXOsApi';
export * from './addressLatestXRPApi';
import { AddressLatestXRPApi } from './addressLatestXRPApi';
export * from './assetsApi';
import { AssetsApi } from './assetsApi';
export * from './blockchainFeesEVMApi';
import { BlockchainFeesEVMApi } from './blockchainFeesEVMApi';
export * from './blockchainFeesKaspaApi';
import { BlockchainFeesKaspaApi } from './blockchainFeesKaspaApi';
export * from './blockchainFeesTezosApi';
import { BlockchainFeesTezosApi } from './blockchainFeesTezosApi';
export * from './blockchainFeesUTXOsApi';
import { BlockchainFeesUTXOsApi } from './blockchainFeesUTXOsApi';
export * from './blockchainFeesXRPApi';
import { BlockchainFeesXRPApi } from './blockchainFeesXRPApi';
export * from './blocksEVMApi';
import { BlocksEVMApi } from './blocksEVMApi';
export * from './blocksUTXOsApi';
import { BlocksUTXOsApi } from './blocksUTXOsApi';
export * from './blocksXRPApi';
import { BlocksXRPApi } from './blocksXRPApi';
export * from './broadcastLocallySignTransactionsApi';
import { BroadcastLocallySignTransactionsApi } from './broadcastLocallySignTransactionsApi';
export * from './contractsEVMApi';
import { ContractsEVMApi } from './contractsEVMApi';
export * from './contractsSolanaApi';
import { ContractsSolanaApi } from './contractsSolanaApi';
export * from './createSubscriptionsForApi';
import { CreateSubscriptionsForApi } from './createSubscriptionsForApi';
export * from './exchangeRatesApi';
import { ExchangeRatesApi } from './exchangeRatesApi';
export * from './featuresApi';
import { FeaturesApi } from './featuresApi';
export * from './hDWalletApi';
import { HDWalletApi } from './hDWalletApi';
export * from './hDWalletDataEVMApi';
import { HDWalletDataEVMApi } from './hDWalletDataEVMApi';
export * from './hDWalletDataUTXOApi';
import { HDWalletDataUTXOApi } from './hDWalletDataUTXOApi';
export * from './hDWalletDataXRPApi';
import { HDWalletDataXRPApi } from './hDWalletDataXRPApi';
export * from './manageAddressesApi';
import { ManageAddressesApi } from './manageAddressesApi';
export * from './manageHDWalletApi';
import { ManageHDWalletApi } from './manageHDWalletApi';
export * from './manageSubscriptionsApi';
import { ManageSubscriptionsApi } from './manageSubscriptionsApi';
export * from './metadataApi';
import { MetadataApi } from './metadataApi';
export * from './prepareTransactionsEVMsApi';
import { PrepareTransactionsEVMsApi } from './prepareTransactionsEVMsApi';
export * from './simulateTransactionsEVMApi';
import { SimulateTransactionsEVMApi } from './simulateTransactionsEVMApi';
export * from './toolsApi';
import { ToolsApi } from './toolsApi';
export * from './toolsEVMApi';
import { ToolsEVMApi } from './toolsEVMApi';
export * from './toolsUTXOsApi';
import { ToolsUTXOsApi } from './toolsUTXOsApi';
export * from './toolsXRPApi';
import { ToolsXRPApi } from './toolsXRPApi';
export * from './transactionsDataEVMApi';
import { TransactionsDataEVMApi } from './transactionsDataEVMApi';
export * from './transactionsDataKaspaApi';
import { TransactionsDataKaspaApi } from './transactionsDataKaspaApi';
export * from './transactionsDataSolanaApi';
import { TransactionsDataSolanaApi } from './transactionsDataSolanaApi';
export * from './transactionsDataUTXOsApi';
import { TransactionsDataUTXOsApi } from './transactionsDataUTXOsApi';
export * from './transactionsDataXRPApi';
import { TransactionsDataXRPApi } from './transactionsDataXRPApi';
export * from './utilsApi';
import { UtilsApi } from './utilsApi';
import * as http from 'http';

export class HttpError extends Error {
    constructor (public response: http.IncomingMessage, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}

export { RequestFile } from '../model/models';

export const APIS = [AMLApi, AddressAMLApi, AddressHistoryApi, AddressHistoryEVMApi, AddressHistoryUTXOsApi, AddressLatestEVMApi, AddressLatestKaspaApi, AddressLatestSolanaApi, AddressLatestUTXOsApi, AddressLatestXRPApi, AssetsApi, BlockchainFeesEVMApi, BlockchainFeesKaspaApi, BlockchainFeesTezosApi, BlockchainFeesUTXOsApi, BlockchainFeesXRPApi, BlocksEVMApi, BlocksUTXOsApi, BlocksXRPApi, BroadcastLocallySignTransactionsApi, ContractsEVMApi, ContractsSolanaApi, CreateSubscriptionsForApi, ExchangeRatesApi, FeaturesApi, HDWalletApi, HDWalletDataEVMApi, HDWalletDataUTXOApi, HDWalletDataXRPApi, ManageAddressesApi, ManageHDWalletApi, ManageSubscriptionsApi, MetadataApi, PrepareTransactionsEVMsApi, SimulateTransactionsEVMApi, ToolsApi, ToolsEVMApi, ToolsUTXOsApi, ToolsXRPApi, TransactionsDataEVMApi, TransactionsDataKaspaApi, TransactionsDataSolanaApi, TransactionsDataUTXOsApi, TransactionsDataXRPApi, UtilsApi];
