/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { EstimateContractInteractionGasLimitEVM400Response } from '../model/estimateContractInteractionGasLimitEVM400Response';
import { EstimateContractInteractionGasLimitEVM401Response } from '../model/estimateContractInteractionGasLimitEVM401Response';
import { EstimateContractInteractionGasLimitEVM403Response } from '../model/estimateContractInteractionGasLimitEVM403Response';
import { EstimateContractInteractionGasLimitEVMR } from '../model/estimateContractInteractionGasLimitEVMR';
import { EstimateContractInteractionGasLimitEVMRB } from '../model/estimateContractInteractionGasLimitEVMRB';
import { EstimateNativeCoinTransferGasLimitEVM400Response } from '../model/estimateNativeCoinTransferGasLimitEVM400Response';
import { EstimateNativeCoinTransferGasLimitEVM401Response } from '../model/estimateNativeCoinTransferGasLimitEVM401Response';
import { EstimateNativeCoinTransferGasLimitEVM403Response } from '../model/estimateNativeCoinTransferGasLimitEVM403Response';
import { EstimateNativeCoinTransferGasLimitEVMR } from '../model/estimateNativeCoinTransferGasLimitEVMR';
import { EstimateNativeCoinTransferGasLimitEVMRB } from '../model/estimateNativeCoinTransferGasLimitEVMRB';
import { EstimateTokenTransferGasLimitEVM400Response } from '../model/estimateTokenTransferGasLimitEVM400Response';
import { EstimateTokenTransferGasLimitEVM401Response } from '../model/estimateTokenTransferGasLimitEVM401Response';
import { EstimateTokenTransferGasLimitEVM403Response } from '../model/estimateTokenTransferGasLimitEVM403Response';
import { EstimateTokenTransferGasLimitEVMR } from '../model/estimateTokenTransferGasLimitEVMR';
import { EstimateTokenTransferGasLimitEVMRB } from '../model/estimateTokenTransferGasLimitEVMRB';
import { GetBlockchainEventSubscriptionDetailsByReferenceID404Response } from '../model/getBlockchainEventSubscriptionDetailsByReferenceID404Response';
import { GetEIP1559FeeRecommendationsEVM400Response } from '../model/getEIP1559FeeRecommendationsEVM400Response';
import { GetEIP1559FeeRecommendationsEVM401Response } from '../model/getEIP1559FeeRecommendationsEVM401Response';
import { GetEIP1559FeeRecommendationsEVM403Response } from '../model/getEIP1559FeeRecommendationsEVM403Response';
import { GetEIP1559FeeRecommendationsEVMR } from '../model/getEIP1559FeeRecommendationsEVMR';
import { GetFeeRecommendationsEVM400Response } from '../model/getFeeRecommendationsEVM400Response';
import { GetFeeRecommendationsEVM401Response } from '../model/getFeeRecommendationsEVM401Response';
import { GetFeeRecommendationsEVM403Response } from '../model/getFeeRecommendationsEVM403Response';
import { GetFeeRecommendationsEVMR } from '../model/getFeeRecommendationsEVMR';
import { GetFeeRecommendationsTRON400Response } from '../model/getFeeRecommendationsTRON400Response';
import { GetFeeRecommendationsTRON401Response } from '../model/getFeeRecommendationsTRON401Response';
import { GetFeeRecommendationsTRON403Response } from '../model/getFeeRecommendationsTRON403Response';
import { GetFeeRecommendationsTRONR } from '../model/getFeeRecommendationsTRONR';
import { VerifyAddress402Response } from '../model/verifyAddress402Response';
import { VerifyAddress409Response } from '../model/verifyAddress409Response';
import { VerifyAddress415Response } from '../model/verifyAddress415Response';
import { VerifyAddress422Response } from '../model/verifyAddress422Response';
import { VerifyAddress429Response } from '../model/verifyAddress429Response';
import { VerifyAddress500Response } from '../model/verifyAddress500Response';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://rest.cryptoapis.io';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum BlockchainFeesEVMApiApiKeys {
    ApiKey,
}

export class BlockchainFeesEVMApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKey': new ApiKeyAuth('header', 'x-api-key'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: BlockchainFeesEVMApiApiKeys, value: string) {
        (this.authentications as any)[BlockchainFeesEVMApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * This endpoint helps customer in estimating the Contract Interaction Gas Limit needed for a transaction. It gives information for gas expenses for a specific contract when calling a specific function.
     * @summary Estimate Contract Interaction Gas Limit EVM
     * @param blockchain Represents the specific blockchain protocol name, e.g. Arbitrum.
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param estimateContractInteractionGasLimitEVMRB 
     */
    public async estimateContractInteractionGasLimitEVM (blockchain: 'arbitrum' | 'avalanche' | 'base' | 'optimism' | 'polygon' | 'tron', network: 'sepolia' | 'mainnet' | 'fuji' | 'amoy' | 'nile', context?: string, estimateContractInteractionGasLimitEVMRB?: EstimateContractInteractionGasLimitEVMRB, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: EstimateContractInteractionGasLimitEVMR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/evm/{blockchain}/{network}/estimate-contract-interaction-gas-limit'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling estimateContractInteractionGasLimitEVM.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling estimateContractInteractionGasLimitEVM.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(estimateContractInteractionGasLimitEVMRB, "EstimateContractInteractionGasLimitEVMRB")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: EstimateContractInteractionGasLimitEVMR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "EstimateContractInteractionGasLimitEVMR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This endpoint helps customer in estimating the gas limit needed for a transaction. It gives information for gas expenses when sending ether to contracts or making a transaction with additional data in it.
     * @summary Estimate Native Coin Transfer Gas Limit EVM
     * @param blockchain Represents the specific blockchain protocol name, e.g. Ethereum.
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param estimateNativeCoinTransferGasLimitEVMRB 
     */
    public async estimateNativeCoinTransferGasLimitEVM (blockchain: 'ethereum' | 'ethereum-classic' | 'binance-smart-chain' | 'arbitrum' | 'avalanche' | 'base' | 'optimism' | 'polygon' | 'tron', network: 'mainnet' | 'mordor' | 'testnet' | 'sepolia' | 'fuji' | 'amoy' | 'nile', context?: string, estimateNativeCoinTransferGasLimitEVMRB?: EstimateNativeCoinTransferGasLimitEVMRB, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: EstimateNativeCoinTransferGasLimitEVMR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/evm/{blockchain}/{network}/estimate-native-coin-transfer-gas-limit'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling estimateNativeCoinTransferGasLimitEVM.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling estimateNativeCoinTransferGasLimitEVM.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(estimateNativeCoinTransferGasLimitEVMRB, "EstimateNativeCoinTransferGasLimitEVMRB")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: EstimateNativeCoinTransferGasLimitEVMR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "EstimateNativeCoinTransferGasLimitEVMR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * This endpoint helps customer in estimating the Contract Gas Limit needed for a transaction. It gives information for gas expenses for a specific contract when sending ethers or making a transaction with additional data in it.
     * @summary Estimate Token Transfer Gas Limit EVM
     * @param blockchain Represents the specific blockchain protocol name, e.g. Ethereum.
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param estimateTokenTransferGasLimitEVMRB 
     */
    public async estimateTokenTransferGasLimitEVM (blockchain: 'ethereum' | 'ethereum-classic' | 'binance-smart-chain' | 'arbitrum' | 'avalanche' | 'base' | 'optimism' | 'polygon' | 'tron', network: 'mainnet' | 'mordor' | 'testnet' | 'sepolia' | 'fuji' | 'amoy' | 'nile', context?: string, estimateTokenTransferGasLimitEVMRB?: EstimateTokenTransferGasLimitEVMRB, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: EstimateTokenTransferGasLimitEVMR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/evm/{blockchain}/{network}/estimate-token-transfer-gas-limit'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling estimateTokenTransferGasLimitEVM.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling estimateTokenTransferGasLimitEVM.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(estimateTokenTransferGasLimitEVMRB, "EstimateTokenTransferGasLimitEVMRB")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: EstimateTokenTransferGasLimitEVMR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "EstimateTokenTransferGasLimitEVMR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Through this endpoint customers can obtain fee recommendations specifically for EIP 1559.
     * @summary Get EIP 1559 Fee Recommendations EVM
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while network like \&quot;testnet\&quot; is a test network.
     * @param blockchain Represents the specific blockchain protocol name, e.g. Ethereum.
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     */
    public async getEIP1559FeeRecommendationsEVM (network: 'mainnet' | 'sepolia' | 'amoy', blockchain: 'ethereum' | 'polygon' | 'optimism' | 'arbitrum' | 'base', context?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: GetEIP1559FeeRecommendationsEVMR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/evm/{blockchain}/{network}/eip-1559'
            .replace('{network}', encodeURIComponent(String(network)))
            .replace('{blockchain}', encodeURIComponent(String(blockchain)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling getEIP1559FeeRecommendationsEVM.');
        }

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling getEIP1559FeeRecommendationsEVM.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: GetEIP1559FeeRecommendationsEVMR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "GetEIP1559FeeRecommendationsEVMR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Through this endpoint customers can obtain fee recommendations. Our fees recommendations are based on Mempool data which makes them much more accurate than fees based on already mined blocks. Calculations are done in real time live.
     * @summary Get Fee Recommendations EVM
     * @param blockchain Represents the specific blockchain protocol name
     * @param network Represents the name of the blockchain network used
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     */
    public async getFeeRecommendationsEVM (blockchain: 'ethereum' | 'ethereum-classic' | 'binance-smart-chain' | 'polygon' | 'optimism' | 'arbitrum' | 'base' | 'avalanche', network: 'mainnet' | 'mordor' | 'testnet' | 'sepolia' | 'amoy' | 'fuji', context?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: GetFeeRecommendationsEVMR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/evm/{blockchain}/{network}/mempool'
            .replace('{blockchain}', encodeURIComponent(String(blockchain)))
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'blockchain' is not null or undefined
        if (blockchain === null || blockchain === undefined) {
            throw new Error('Required parameter blockchain was null or undefined when calling getFeeRecommendationsEVM.');
        }

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling getFeeRecommendationsEVM.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: GetFeeRecommendationsEVMR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "GetFeeRecommendationsEVMR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Through this endpoint customers can obtain fee recommendations. Our fees recommendations are based on Mempool data which makes them much more accurate than fees based on already mined blocks. Calculations are done in real time live.
     * @summary Get Fee Recommendations TRON
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     */
    public async getFeeRecommendationsTRON (network: 'nile' | 'mainnet', context?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: GetFeeRecommendationsTRONR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/evm/tron/{network}/mempool'
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling getFeeRecommendationsTRON.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: GetFeeRecommendationsTRONR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "GetFeeRecommendationsTRONR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
