/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { EstimateFA12TransferFeeTezos400Response } from '../model/estimateFA12TransferFeeTezos400Response';
import { EstimateFA12TransferFeeTezos401Response } from '../model/estimateFA12TransferFeeTezos401Response';
import { EstimateFA12TransferFeeTezos403Response } from '../model/estimateFA12TransferFeeTezos403Response';
import { EstimateFA12TransferFeeTezosR } from '../model/estimateFA12TransferFeeTezosR';
import { EstimateFA12TransferFeeTezosRB } from '../model/estimateFA12TransferFeeTezosRB';
import { EstimateFA2TransferFeeTezos400Response } from '../model/estimateFA2TransferFeeTezos400Response';
import { EstimateFA2TransferFeeTezos401Response } from '../model/estimateFA2TransferFeeTezos401Response';
import { EstimateFA2TransferFeeTezos403Response } from '../model/estimateFA2TransferFeeTezos403Response';
import { EstimateFA2TransferFeeTezosR } from '../model/estimateFA2TransferFeeTezosR';
import { EstimateFA2TransferFeeTezosRB } from '../model/estimateFA2TransferFeeTezosRB';
import { EstimateTransferFeeTezos400Response } from '../model/estimateTransferFeeTezos400Response';
import { EstimateTransferFeeTezos401Response } from '../model/estimateTransferFeeTezos401Response';
import { EstimateTransferFeeTezos403Response } from '../model/estimateTransferFeeTezos403Response';
import { EstimateTransferFeeTezosR } from '../model/estimateTransferFeeTezosR';
import { EstimateTransferFeeTezosRB } from '../model/estimateTransferFeeTezosRB';
import { GetFeeRecommendationsTezos400Response } from '../model/getFeeRecommendationsTezos400Response';
import { GetFeeRecommendationsTezos401Response } from '../model/getFeeRecommendationsTezos401Response';
import { GetFeeRecommendationsTezos403Response } from '../model/getFeeRecommendationsTezos403Response';
import { GetFeeRecommendationsTezosR } from '../model/getFeeRecommendationsTezosR';
import { VerifyAddress402Response } from '../model/verifyAddress402Response';
import { VerifyAddress409Response } from '../model/verifyAddress409Response';
import { VerifyAddress415Response } from '../model/verifyAddress415Response';
import { VerifyAddress422Response } from '../model/verifyAddress422Response';
import { VerifyAddress429Response } from '../model/verifyAddress429Response';
import { VerifyAddress500Response } from '../model/verifyAddress500Response';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://rest.cryptoapis.io';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum BlockchainFeesTezosApiApiKeys {
    ApiKey,
}

export class BlockchainFeesTezosApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKey': new ApiKeyAuth('header', 'x-api-key'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: BlockchainFeesTezosApiApiKeys, value: string) {
        (this.authentications as any)[BlockchainFeesTezosApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Returns a fee estimate for transferring an FA1.2 token on Tezos. FA1.2 is Tezos\'s single-asset token standard - used by major tokens such as USDt on Tezos.
     * @summary Estimate FA1.2 Transfer Fee Tezos
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param estimateFA12TransferFeeTezosRB 
     */
    public async estimateFA12TransferFeeTezos (network: 'shadownet' | 'mainnet', context?: string, estimateFA12TransferFeeTezosRB?: EstimateFA12TransferFeeTezosRB, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: EstimateFA12TransferFeeTezosR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/tezos/{network}/estimate-fa12-transfer'
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling estimateFA12TransferFeeTezos.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(estimateFA12TransferFeeTezosRB, "EstimateFA12TransferFeeTezosRB")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: EstimateFA12TransferFeeTezosR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "EstimateFA12TransferFeeTezosR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns a fee estimate for transferring an FA2 token on Tezos. FA2 (TZIP-12) is Tezos\'s multi-asset token standard - it powers NFTs, gaming assets, and most fungible tokens minted from 2021 onward. A single FA2 contract can hold many distinct tokens, identified by a numeric tokenId, so this endpoint requires that id alongside the contract address.
     * @summary Estimate FA2 Transfer Fee Tezos
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param estimateFA2TransferFeeTezosRB 
     */
    public async estimateFA2TransferFeeTezos (network: 'shadownet' | 'mainnet', context?: string, estimateFA2TransferFeeTezosRB?: EstimateFA2TransferFeeTezosRB, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: EstimateFA2TransferFeeTezosR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/tezos/{network}/estimate-fa2-transfer'
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling estimateFA2TransferFeeTezos.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(estimateFA2TransferFeeTezosRB, "EstimateFA2TransferFeeTezosRB")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: EstimateFA2TransferFeeTezosR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "EstimateFA2TransferFeeTezosR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Returns a fee estimate for a native XTZ transfer between two Tezos accounts.
     * @summary Estimate Transfer Fee Tezos
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     * @param estimateTransferFeeTezosRB 
     */
    public async estimateTransferFeeTezos (network: 'shadownet' | 'mainnet', context?: string, estimateTransferFeeTezosRB?: EstimateTransferFeeTezosRB, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: EstimateTransferFeeTezosR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/tezos/{network}/estimate-transfer'
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling estimateTransferFeeTezos.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(estimateTransferFeeTezosRB, "EstimateTransferFeeTezosRB")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: EstimateTransferFeeTezosR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "EstimateTransferFeeTezosR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Through this endpoint customers can obtain fee recommendations. Our fees recommendations are based on Mempool data which makes them much more accurate than fees based on already mined blocks. Calculations are done in real time live.
     * @summary Get Fee Recommendations Tezos
     * @param network Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \&quot;mainnet\&quot; is the live network with actual data while networks like \&quot;testnet\&quot;
     * @param context In batch situations the user can use the context to correlate responses with requests. This property is present regardless of whether the response was successful or returned as an error. &#x60;context&#x60; is specified by the user.
     */
    public async getFeeRecommendationsTezos (network: 'shadownet' | 'mainnet', context?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: GetFeeRecommendationsTezosR;  }> {
        const localVarPath = this.basePath + '/blockchain-fees/tezos/{network}/mempool'
            .replace('{network}', encodeURIComponent(String(network)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'network' is not null or undefined
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling getFeeRecommendationsTezos.');
        }

        if (context !== undefined) {
            localVarQueryParameters['context'] = ObjectSerializer.serialize(context, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKey.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKey.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: GetFeeRecommendationsTezosR;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "GetFeeRecommendationsTezosR");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
