/**
 * The ONE OWNER of "where the app-side site scaffold lives".
 *
 * WHY THIS EXPORTS A PATH RATHER THAN LETTING CALLERS BUILD ONE (measured 2026-08-27):
 * before this file, four places independently re-derived the same directory — the CLI's
 * Hydrator SCAFFOLDS_DIR, the generator's Core output row, and two app-sdk tests, each
 * spelling out `descix-cli/templates/scaffolds/site` by hand. Two derivations of one fact
 * WILL disagree silently; four is a guarantee. Every consumer now imports this constant,
 * so moving the directory is a one-line change that cannot leave a stale reader behind.
 *
 * It is a directory of PLAIN BROWSER FILES (no build step, no module loader), copied
 * verbatim into a developer's app/. `DeSciXAppSDK.js` inside it is GENERATED by
 * scripts/generate-app-sdk-copies.js from templates/DeSciXAppSDK.template.js +
 * src/util/bridgeResolver.js — do not hand-edit it, and do not add a second copy of it
 * anywhere; add an output row to the generator instead.
 */
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the site scaffold directory shipped inside this package. */
export const SITE_SCAFFOLD_DIR = join(HERE, 'site');

/** Absolute path to the generated app-side bridge inside the site scaffold. */
export const SITE_SCAFFOLD_BRIDGE = join(SITE_SCAFFOLD_DIR, 'DeSciXAppSDK.js');

/**
 * Materialize the site scaffold into `targetDir`.
 *
 * Deliberately dumb: the scaffold is plain browser files with no build step, so "materialize" is
 * a verbatim recursive copy and nothing else. It needs no workspace, no auth and no platform
 * call, which is what lets `@descix/sdk/app`'s bin offer `init` while every platform-side verb
 * stays a served MCP verb.
 *
 * IT DOES NOT SUBSTITUTE, AND THE DIRECTORY DOES CARRY PLACEHOLDERS. site/index.html and
 * site/app.js hold {{APP_NAME}}, so anything materialized through THIS entry point ships literal
 * braces to a developer. The CLI's own path resolves them (descix-cli Hydrator::copyScaffold,
 * which the `descix site init` command drives with the workspace's real ids). This function
 * cannot do the same as written: its only inputs are a target directory and `force` — it has no
 * app id and no community id to substitute, precisely because it takes no workspace and no auth.
 * Closing that is a design decision about what `descix-app init` should ask for, not something to
 * paper over with a guessed default.
 *
 * REFUSES rather than merges when the target is non-empty: silently copying over a developer's
 * edited app.js is unrecoverable, and "it looked like it worked" is the failure mode that
 * costs the most to discover.
 */
export async function copySiteScaffold(targetDir, { force = false } = {}) {
  const { cp, readdir, mkdir } = await import('node:fs/promises');

  let existing = [];
  try {
    existing = await readdir(targetDir);
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }

  if (existing.length > 0 && !force) {
    throw new Error(
      `${targetDir} already contains ${existing.length} entr${existing.length === 1 ? 'y' : 'ies'}. ` +
      `Refusing to overwrite a developer's app. Pass --force if that is what you mean.`
    );
  }

  await mkdir(targetDir, { recursive: true });
  await cp(SITE_SCAFFOLD_DIR, targetDir, { recursive: true, force: true });
  return (await readdir(targetDir)).sort();
}
