/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* OMNI
*/
export class AddressTokensTransactionConfirmedEachConfirmationOmni {
    /**
    * Specifies the name of the token.
    */
    'name': string;
    /**
    * Defines the ID of the property for Omni Layer.
    */
    'propertyId': string;
    /**
    * Defines the type of the transaction.
    */
    'transactionType': string;
    /**
    * The transaction ID used to create the token.
    */
    'createdByTransactionId': string;
    /**
    * Defines the amount of tokens sent with the confirmed transaction.
    */
    'amount': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "propertyId",
            "baseName": "propertyId",
            "type": "string"
        },
        {
            "name": "transactionType",
            "baseName": "transactionType",
            "type": "string"
        },
        {
            "name": "createdByTransactionId",
            "baseName": "createdByTransactionId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AddressTokensTransactionConfirmedEachConfirmationOmni.attributeTypeMap;
    }
}

