/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddressInternalTransactionConfirmedDataItemMinedInBlock } from './addressInternalTransactionConfirmedDataItemMinedInBlock';

/**
* Defines an `item` as one result.
*/
export class AddressInternalTransactionConfirmedDataItem {
    /**
    * Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc.
    */
    'blockchain': string;
    /**
    * Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \"mainnet\" is the live network with actual data while networks like \"testnet\", \"sepolia\" are test networks.
    */
    'network': string;
    /**
    * Defines the specific address of the internal transaction.
    */
    'address': string;
    'minedInBlock': AddressInternalTransactionConfirmedDataItemMinedInBlock;
    /**
    * Defines the Parent Transaction\'s unique ID.
    */
    'parentTransactionId': string;
    /**
    * Defines the specific operation\'s unique ID.
    */
    'operationId': string;
    /**
    * Defines the amount of coins sent with the confirmed transaction.
    */
    'amount': string;
    /**
    * Defines the unit of the transaction, e.g. Gwei.
    */
    'unit': string;
    /**
    * Defines whether the transaction is \"incoming\" or \"outgoing\".
    */
    'direction': AddressInternalTransactionConfirmedDataItem.DirectionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockchain",
            "baseName": "blockchain",
            "type": "string"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "minedInBlock",
            "baseName": "minedInBlock",
            "type": "AddressInternalTransactionConfirmedDataItemMinedInBlock"
        },
        {
            "name": "parentTransactionId",
            "baseName": "parentTransactionId",
            "type": "string"
        },
        {
            "name": "operationId",
            "baseName": "operationId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "AddressInternalTransactionConfirmedDataItem.DirectionEnum"
        }    ];

    static getAttributeTypeMap() {
        return AddressInternalTransactionConfirmedDataItem.attributeTypeMap;
    }
}

export namespace AddressInternalTransactionConfirmedDataItem {
    export enum DirectionEnum {
        Incoming = <any> 'incoming',
        Outgoing = <any> 'outgoing'
    }
}
