/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* ERC-721
*/
export class AddressTokensTransactionConfirmedErc721 {
    /**
    * Specifies the name of the token.
    */
    'name': string;
    /**
    * Specifies an identifier of the token, where up to five alphanumeric characters can be used for it.
    */
    'symbol': string;
    /**
    * Specifies the ID of the token.
    */
    'tokenId': string;
    /**
    * Specifies the address of the contract.
    */
    'contractAddress': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "tokenId",
            "baseName": "tokenId",
            "type": "string"
        },
        {
            "name": "contractAddress",
            "baseName": "contractAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AddressTokensTransactionConfirmedErc721.attributeTypeMap;
    }
}

