/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddressTokensTransactionConfirmedDataItem } from './addressTokensTransactionConfirmedDataItem';

/**
* Specifies all data, as attributes, included into the callback notification, which depends on the `event`.
*/
export class AddressTokensTransactionConfirmedData {
    /**
    * Represents the Crypto APIs 2.0 product which sends the callback.
    */
    'product': string;
    /**
    * Defines the specific event, for which a callback subscription is set.
    */
    'event': string;
    'item': AddressTokensTransactionConfirmedDataItem;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "product",
            "baseName": "product",
            "type": "string"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "string"
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "AddressTokensTransactionConfirmedDataItem"
        }    ];

    static getAttributeTypeMap() {
        return AddressTokensTransactionConfirmedData.attributeTypeMap;
    }
}

