/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DecodeRawTransactionHexEVMRIBSEFee {
    /**
    * Defines the maximum amount that customer is willing to pay per unit of gas to get his transaction included in a block.
    */
    'maxFeePerGas'?: string;
    /**
    * Represents determined by the user value that is paid directly to miners.
    */
    'maxPrioriryFeePerGas'?: string;
    /**
    * String representation of the fee unit
    */
    'unit': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "maxFeePerGas",
            "baseName": "maxFeePerGas",
            "type": "string"
        },
        {
            "name": "maxPrioriryFeePerGas",
            "baseName": "maxPrioriryFeePerGas",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DecodeRawTransactionHexEVMRIBSEFee.attributeTypeMap;
    }
}

