/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DeriveAndSyncNewChangeAddressesUTXORI {
    /**
    * Represents the public address, which is a compressed and shortened form of a public key.
    */
    'address': string;
    /**
    * Represents the format of the address.
    */
    'format': string;
    /**
    * Represent the address derivation index
    */
    'index': number;
    /**
    * Represents the derivation type
    */
    'derivationType': DeriveAndSyncNewChangeAddressesUTXORI.DerivationTypeEnum;
    /**
    * Defines the address type.
    */
    'type': DeriveAndSyncNewChangeAddressesUTXORI.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number"
        },
        {
            "name": "derivationType",
            "baseName": "derivationType",
            "type": "DeriveAndSyncNewChangeAddressesUTXORI.DerivationTypeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DeriveAndSyncNewChangeAddressesUTXORI.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return DeriveAndSyncNewChangeAddressesUTXORI.attributeTypeMap;
    }
}

export namespace DeriveAndSyncNewChangeAddressesUTXORI {
    export enum DerivationTypeEnum {
        Account = <any> 'account',
        Bip32 = <any> 'bip32'
    }
    export enum TypeEnum {
        Change = <any> 'change'
    }
}
