/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetAddressStatisticsEVMRIInternalTransactionsCounts } from './getAddressStatisticsEVMRIInternalTransactionsCounts';
import { GetAddressStatisticsEVMRINativeTransactionsCounts } from './getAddressStatisticsEVMRINativeTransactionsCounts';
import { GetAddressStatisticsEVMRITokenTransfersCounts } from './getAddressStatisticsEVMRITokenTransfersCounts';

export class GetAddressStatisticsEVMRI {
    /**
    * String representation of the EVM address
    */
    'address': string;
    /**
    * Numeric representation of the current block height
    */
    'blockHeight': number;
    /**
    * Numeric representation of the current block timestamp in seconds since Unix epoch.
    */
    'blockTimestamp': number;
    'internalTransactionsCounts': GetAddressStatisticsEVMRIInternalTransactionsCounts;
    'nativeTransactionsCounts': GetAddressStatisticsEVMRINativeTransactionsCounts;
    'tokenTransfersCounts': GetAddressStatisticsEVMRITokenTransfersCounts;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "blockHeight",
            "baseName": "blockHeight",
            "type": "number"
        },
        {
            "name": "blockTimestamp",
            "baseName": "blockTimestamp",
            "type": "number"
        },
        {
            "name": "internalTransactionsCounts",
            "baseName": "internalTransactionsCounts",
            "type": "GetAddressStatisticsEVMRIInternalTransactionsCounts"
        },
        {
            "name": "nativeTransactionsCounts",
            "baseName": "nativeTransactionsCounts",
            "type": "GetAddressStatisticsEVMRINativeTransactionsCounts"
        },
        {
            "name": "tokenTransfersCounts",
            "baseName": "tokenTransfersCounts",
            "type": "GetAddressStatisticsEVMRITokenTransfersCounts"
        }    ];

    static getAttributeTypeMap() {
        return GetAddressStatisticsEVMRI.attributeTypeMap;
    }
}

