/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetAddressStatisticsUTXOsRITransactionCounts } from './getAddressStatisticsUTXOsRITransactionCounts';

export class GetAddressStatisticsUTXOsRI {
    /**
    * String representation of the address
    */
    'address': string;
    /**
    * Numeric representation of the current blockchain block height
    */
    'blockHeight': number;
    /**
    * Numeric representation of the current blockchain block timestamp
    */
    'blockTimestamp': number;
    'transactionCounts': GetAddressStatisticsUTXOsRITransactionCounts;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "blockHeight",
            "baseName": "blockHeight",
            "type": "number"
        },
        {
            "name": "blockTimestamp",
            "baseName": "blockTimestamp",
            "type": "number"
        },
        {
            "name": "transactionCounts",
            "baseName": "transactionCounts",
            "type": "GetAddressStatisticsUTXOsRITransactionCounts"
        }    ];

    static getAttributeTypeMap() {
        return GetAddressStatisticsUTXOsRI.attributeTypeMap;
    }
}

