/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetBlockDetailsByBlockHeightUTXOsRI {
    /**
    * Numeric representation of the Block bits
    */
    'bits': number;
    /**
    * Numeric representation of the expected number of hashes required to produce the chain up to this block
    */
    'chainwork': number;
    /**
    * Numeric representation of the block difficulty
    */
    'difficulty': number;
    /**
    * String representation of the block hash
    */
    'hash': string;
    /**
    * Numeric representation of the block height
    */
    'height': number;
    /**
    * String representation of the block merkle root
    */
    'merkleRoot': string;
    /**
    * String representation of the next block hash
    */
    'nextBlockHash': string;
    /**
    * String representation of the previous block hash
    */
    'previousBlockHash': string;
    /**
    * Numeric representation of the block size
    */
    'size': number;
    /**
    * Numeric representation of the block timestamp in seconds since epoch
    */
    'timestamp': number;
    /**
    * Numeric representation of the block transactions count
    */
    'transactionsCount': number;
    /**
    * Numeric representation of the block version
    */
    'version': number;
    /**
    * Numeric representation of the block size excluding witness data
    */
    'strippedSize': number;
    /**
    * String representation of the block version in hexadecimal format
    */
    'versionHex': string;
    /**
    * Numeric representation of block weight
    */
    'weight': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bits",
            "baseName": "bits",
            "type": "number"
        },
        {
            "name": "chainwork",
            "baseName": "chainwork",
            "type": "number"
        },
        {
            "name": "difficulty",
            "baseName": "difficulty",
            "type": "number"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "merkleRoot",
            "baseName": "merkleRoot",
            "type": "string"
        },
        {
            "name": "nextBlockHash",
            "baseName": "nextBlockHash",
            "type": "string"
        },
        {
            "name": "previousBlockHash",
            "baseName": "previousBlockHash",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "transactionsCount",
            "baseName": "transactionsCount",
            "type": "number"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "strippedSize",
            "baseName": "strippedSize",
            "type": "number"
        },
        {
            "name": "versionHex",
            "baseName": "versionHex",
            "type": "string"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetBlockDetailsByBlockHeightUTXOsRI.attributeTypeMap;
    }
}

