/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetBlockDetailsByBlockHeightEVMRI {
    /**
    * Represents the hash of the block, which is its unique identifier. It represents a cryptographic digital fingerprint made by hashing the block header twice through the SHA256 algorithm.
    */
    'hash': string;
    /**
    * Represents the number of blocks in the blockchain preceding this specific block. Block numbers have no gaps. A blockchain usually starts with block 0 called the \"Genesis block\".
    */
    'height': number;
    /**
    * Representation of the next block hash.
    */
    'nextBlockHash'?: string;
    /**
    * Represents the hash of the previous block, also known as the parent block.
    */
    'previousBlockHash': string;
    /**
    * Numeric representation of the block size
    */
    'size': number;
    /**
    * Defines the exact date/time when this block was mined in Unix Timestamp.
    */
    'timestamp': number;
    /**
    * Represents the total number of all transactions as part of this block.
    */
    'transactionsCount': number;
    /**
    * Represents any data that can be included by the miner in the block.
    */
    'extraData': string;
    /**
    * Numeric representation of the block gas limit
    */
    'gasLimit': number;
    /**
    * Numeric representation of the block gas used
    */
    'gasUsed': number;
    /**
    * Numeric representation of the block gas limit
    */
    'minedInSeconds': number;
    /**
    * Numeric representation of the block nonce
    */
    'nonce': number;
    /**
    * Numeric representation of the block total difficulty
    */
    'totalDifficulty': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "nextBlockHash",
            "baseName": "nextBlockHash",
            "type": "string"
        },
        {
            "name": "previousBlockHash",
            "baseName": "previousBlockHash",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "transactionsCount",
            "baseName": "transactionsCount",
            "type": "number"
        },
        {
            "name": "extraData",
            "baseName": "extraData",
            "type": "string"
        },
        {
            "name": "gasLimit",
            "baseName": "gasLimit",
            "type": "number"
        },
        {
            "name": "gasUsed",
            "baseName": "gasUsed",
            "type": "number"
        },
        {
            "name": "minedInSeconds",
            "baseName": "minedInSeconds",
            "type": "number"
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "number"
        },
        {
            "name": "totalDifficulty",
            "baseName": "totalDifficulty",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetBlockDetailsByBlockHeightEVMRI.attributeTypeMap;
    }
}

