/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetTransactionDetailsByTransactionHashEVMRIBSE } from './getTransactionDetailsByTransactionHashEVMRIBSE';
import { GetTransactionDetailsByTransactionHashEVMRIFee } from './getTransactionDetailsByTransactionHashEVMRIFee';
import { GetTransactionDetailsByTransactionHashEVMRIGasPrice } from './getTransactionDetailsByTransactionHashEVMRIGasPrice';
import { GetTransactionDetailsByTransactionHashEVMRIMinedInBlock } from './getTransactionDetailsByTransactionHashEVMRIMinedInBlock';
import { GetTransactionDetailsByTransactionHashEVMRIValue } from './getTransactionDetailsByTransactionHashEVMRIValue';

export class GetTransactionDetailsByTransactionHashEVMRI {
    /**
    * String representation of the transaction contract address
    */
    'contract'?: string;
    'fee': GetTransactionDetailsByTransactionHashEVMRIFee;
    /**
    * String representation of the transaction gas limit
    */
    'gasLimit': number;
    /**
    * String representation of the transaction used gas
    */
    'gasUsed': number;
    /**
    * String representation of the transaction hash
    */
    'hash': string;
    /**
    * String representation of the transaction input data
    */
    'inputData': string;
    /**
    * Numeric representation of the transaction nonce
    */
    'nonce': number;
    /**
    * Numeric representation of the transaction index
    */
    'positionInBlock': number;
    /**
    * String representation of the recipient address
    */
    'recipient': string;
    /**
    * String representation of the sender address
    */
    'sender': string;
    /**
    * String representation of the transaction status
    */
    'status': string;
    /**
    * Numeric representation of the timestamp in seconds since epoch
    */
    'timestamp': number;
    'value': GetTransactionDetailsByTransactionHashEVMRIValue;
    'gasPrice': GetTransactionDetailsByTransactionHashEVMRIGasPrice;
    'minedInBlock': GetTransactionDetailsByTransactionHashEVMRIMinedInBlock;
    'blockchainSpecific'?: GetTransactionDetailsByTransactionHashEVMRIBSE;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contract",
            "baseName": "contract",
            "type": "string"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "GetTransactionDetailsByTransactionHashEVMRIFee"
        },
        {
            "name": "gasLimit",
            "baseName": "gasLimit",
            "type": "number"
        },
        {
            "name": "gasUsed",
            "baseName": "gasUsed",
            "type": "number"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "inputData",
            "baseName": "inputData",
            "type": "string"
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "number"
        },
        {
            "name": "positionInBlock",
            "baseName": "positionInBlock",
            "type": "number"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "GetTransactionDetailsByTransactionHashEVMRIValue"
        },
        {
            "name": "gasPrice",
            "baseName": "gasPrice",
            "type": "GetTransactionDetailsByTransactionHashEVMRIGasPrice"
        },
        {
            "name": "minedInBlock",
            "baseName": "minedInBlock",
            "type": "GetTransactionDetailsByTransactionHashEVMRIMinedInBlock"
        },
        {
            "name": "blockchainSpecific",
            "baseName": "blockchainSpecific",
            "type": "GetTransactionDetailsByTransactionHashEVMRIBSE"
        }    ];

    static getAttributeTypeMap() {
        return GetTransactionDetailsByTransactionHashEVMRI.attributeTypeMap;
    }
}

