/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetTransactionDetailsByTransactionIdKaspaRIFee } from './getTransactionDetailsByTransactionIdKaspaRIFee';
import { GetTransactionDetailsByTransactionIdKaspaRIInputsInner } from './getTransactionDetailsByTransactionIdKaspaRIInputsInner';
import { GetTransactionDetailsByTransactionIdKaspaRIOutputsInner } from './getTransactionDetailsByTransactionIdKaspaRIOutputsInner';

export class GetTransactionDetailsByTransactionIdKaspaRI {
    'blocksHashes': Array<string>;
    'fee'?: GetTransactionDetailsByTransactionIdKaspaRIFee;
    /**
    * String representation of the transaction hash
    */
    'hash': string;
    /**
    * String representation of the transaction ID
    */
    'id': string;
    /**
    * Transaction inputs
    */
    'inputs': Array<GetTransactionDetailsByTransactionIdKaspaRIInputsInner>;
    /**
    * Transaction outputs
    */
    'outputs': Array<GetTransactionDetailsByTransactionIdKaspaRIOutputsInner>;
    /**
    * Timestamp of the transaction
    */
    'timestamp': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blocksHashes",
            "baseName": "blocksHashes",
            "type": "Array<string>"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "GetTransactionDetailsByTransactionIdKaspaRIFee"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "Array<GetTransactionDetailsByTransactionIdKaspaRIInputsInner>"
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "Array<GetTransactionDetailsByTransactionIdKaspaRIOutputsInner>"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetTransactionDetailsByTransactionIdKaspaRI.attributeTypeMap;
    }
}

