/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Specifies the latest price of the asset.
*/
export class ListSupportedAssetsRILatestRate {
    /**
    * Represents the amount of the latest rate.
    */
    'amount': string;
    /**
    * Defines when the price was calculated in UNIX timestamp. Oldest possible timestamp is 30 days.
    */
    'calculationTimestamp'?: number;
    /**
    * Specifies the unit of the latest price of the asset.
    */
    'unit': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "calculationTimestamp",
            "baseName": "calculationTimestamp",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListSupportedAssetsRILatestRate.attributeTypeMap;
    }
}

