/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ListSyncedHDWalletsXPubYPubZPubRI {
    /**
    * Defines the account extended publicly known key which is used to derive all child public keys.
    */
    'extendedPublicKey': string;
    /**
    * Defines the activation status of the hd wallet - if it is active or not.
    */
    'isActive': boolean;
    /**
    * Defines the sync status of the hd wallet - if it is synced or not.
    */
    'syncStatus': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "extendedPublicKey",
            "baseName": "extendedPublicKey",
            "type": "string"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "syncStatus",
            "baseName": "syncStatus",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListSyncedHDWalletsXPubYPubZPubRI.attributeTypeMap;
    }
}

