/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListTransactionsByAddressSolanaRIFee } from './listTransactionsByAddressSolanaRIFee';
import { ListTransactionsByAddressSolanaRIMinedInBlock } from './listTransactionsByAddressSolanaRIMinedInBlock';
import { ListTransactionsByAddressSolanaRINativeBalanceChangesInner } from './listTransactionsByAddressSolanaRINativeBalanceChangesInner';
import { ListTransactionsByAddressSolanaRINativeMovementsInner } from './listTransactionsByAddressSolanaRINativeMovementsInner';
import { ListTransactionsByAddressSolanaRITokenBalanceChangesInner } from './listTransactionsByAddressSolanaRITokenBalanceChangesInner';
import { ListTransactionsByAddressSolanaRITokenMovementsInner } from './listTransactionsByAddressSolanaRITokenMovementsInner';

export class ListTransactionsByAddressSolanaRI {
    'fee': ListTransactionsByAddressSolanaRIFee;
    /**
    * Object Array representation of the transactions native (SOL) balance changes of each address
    */
    'nativeBalanceChanges': Array<ListTransactionsByAddressSolanaRINativeBalanceChangesInner>;
    /**
    * Object Array representation of the transactions native movements
    */
    'nativeMovements': Array<ListTransactionsByAddressSolanaRINativeMovementsInner>;
    /**
    * String representation of the transaction\'s signature
    */
    'signature': string;
    /**
    * String representation of the transaction\'s signer
    */
    'signer': string;
    /**
    * Numeric representation of the transaction\'s timestamp
    */
    'timestamp': number;
    /**
    * Object Array representation of the transactions token (SPL) balance changes of each address and token
    */
    'tokenBalanceChanges': Array<ListTransactionsByAddressSolanaRITokenBalanceChangesInner>;
    /**
    * Object Array representation of the transactions token movements
    */
    'tokenMovements': Array<ListTransactionsByAddressSolanaRITokenMovementsInner>;
    'minedInBlock': ListTransactionsByAddressSolanaRIMinedInBlock;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListTransactionsByAddressSolanaRIFee"
        },
        {
            "name": "nativeBalanceChanges",
            "baseName": "nativeBalanceChanges",
            "type": "Array<ListTransactionsByAddressSolanaRINativeBalanceChangesInner>"
        },
        {
            "name": "nativeMovements",
            "baseName": "nativeMovements",
            "type": "Array<ListTransactionsByAddressSolanaRINativeMovementsInner>"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "string"
        },
        {
            "name": "signer",
            "baseName": "signer",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "tokenBalanceChanges",
            "baseName": "tokenBalanceChanges",
            "type": "Array<ListTransactionsByAddressSolanaRITokenBalanceChangesInner>"
        },
        {
            "name": "tokenMovements",
            "baseName": "tokenMovements",
            "type": "Array<ListTransactionsByAddressSolanaRITokenMovementsInner>"
        },
        {
            "name": "minedInBlock",
            "baseName": "minedInBlock",
            "type": "ListTransactionsByAddressSolanaRIMinedInBlock"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactionsByAddressSolanaRI.attributeTypeMap;
    }
}

