/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListBlockchainEventsSubscriptionsRIDeactivationReasonsInner } from './listBlockchainEventsSubscriptionsRIDeactivationReasonsInner';

export class ListBlockchainEventsSubscriptionsRI {
    /**
    * Represents the address of the transaction.
    */
    'address': string;
    /**
    * Represents the Secret Key value provided by the customer. This field is used for security purposes during the callback notification, in order to prove the sender of the callback as Crypto APIs. For more information please see our [Documentation](https://project-2a14af.doxify.ai/v-1.2023-04-25-105/RESTapis/general-information/callbacks#callback-security).
    */
    'callbackSecretKey'?: string;
    /**
    * Represents the URL that is set by the customer where the callback will be received at. The callback notification will be received only if and when the event occurs. `We support ONLY httpS type of protocol`.
    */
    'callbackUrl': string;
    /**
    * Represents the number of confirmations, i.e. the amount of blocks that have been built on top of this block.
    */
    'confirmationsCount': number;
    /**
    * Defines the specific time/date when the subscription was created in Unix Timestamp.
    */
    'createdTimestamp': number;
    /**
    * Represents the deactivation reason details, available when a blockchain event subscription has status isActive - false.
    */
    'deactivationReasons'?: Array<ListBlockchainEventsSubscriptionsRIDeactivationReasonsInner>;
    /**
    * Defines the type of the specific event available for the customer to subscribe to for callback notification.
    */
    'eventType': string;
    /**
    * Defines whether the subscription is active or not. Set as boolean.
    */
    'isActive': boolean;
    /**
    * Represents a unique ID used to reference the specific callback subscription.
    */
    'referenceId': string;
    /**
    * Represents the unique identification string that defines the transaction.
    */
    'transactionId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "callbackSecretKey",
            "baseName": "callbackSecretKey",
            "type": "string"
        },
        {
            "name": "callbackUrl",
            "baseName": "callbackUrl",
            "type": "string"
        },
        {
            "name": "confirmationsCount",
            "baseName": "confirmationsCount",
            "type": "number"
        },
        {
            "name": "createdTimestamp",
            "baseName": "createdTimestamp",
            "type": "number"
        },
        {
            "name": "deactivationReasons",
            "baseName": "deactivationReasons",
            "type": "Array<ListBlockchainEventsSubscriptionsRIDeactivationReasonsInner>"
        },
        {
            "name": "eventType",
            "baseName": "eventType",
            "type": "string"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "referenceId",
            "baseName": "referenceId",
            "type": "string"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListBlockchainEventsSubscriptionsRI.attributeTypeMap;
    }
}

