/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIInputsInnerScript } from './listConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIInputsInnerScript';
import { ListTransactionsByBlockHashUTXOsRIInputsInnerValue } from './listTransactionsByBlockHashUTXOsRIInputsInnerValue';

export class ListTransactionsByBlockHashUTXOsRIInputsInner {
    'addresses'?: Array<string>;
    /**
    * Represents the coinbase hex.
    */
    'coinbase'?: string;
    /**
    * It refers to the index of the output address of this transaction. The index starts from 0.
    */
    'oututIndex': number;
    'script': ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIInputsInnerScript;
    /**
    * Represents the reference transaction identifier.
    */
    'transactionId': string;
    'value'?: ListTransactionsByBlockHashUTXOsRIInputsInnerValue;
    'witnesses': Array<string>;
    /**
    * It refers to the index of the output address of this transaction. The index starts from 0.
    */
    'outputIndex': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<string>"
        },
        {
            "name": "coinbase",
            "baseName": "coinbase",
            "type": "string"
        },
        {
            "name": "oututIndex",
            "baseName": "oututIndex",
            "type": "number"
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIInputsInnerScript"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ListTransactionsByBlockHashUTXOsRIInputsInnerValue"
        },
        {
            "name": "witnesses",
            "baseName": "witnesses",
            "type": "Array<string>"
        },
        {
            "name": "outputIndex",
            "baseName": "outputIndex",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactionsByBlockHashUTXOsRIInputsInner.attributeTypeMap;
    }
}

