/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIFee } from './listConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIFee';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIInputsInner } from './listConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIInputsInner';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIMinedInBlock } from './listConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIMinedInBlock';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIOutputsInner } from './listConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIOutputsInner';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIRecipientsInner } from './listConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIRecipientsInner';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRISendersInner } from './listConfirmedTransactionsByAddressByTimestampUTXOHistoricalRISendersInner';

export class ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRI {
    'fee': ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIFee;
    /**
    * String representation of the transaction hash
    */
    'hash': string;
    /**
    * String representation of the transaction identifier (txid)
    */
    'id': string;
    /**
    * Object Array representation of transaction inputs
    */
    'inputs': Array<ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIInputsInner>;
    /**
    * Numeric representation of the transaction locktime
    */
    'locktime': number;
    /**
    * Object Array representation of transaction outputs
    */
    'outputs': Array<ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIOutputsInner>;
    /**
    * Numeric representation of the index
    */
    'positionInBlock': number;
    /**
    * Object Array representation of transaction receivers
    */
    'recipients': Array<ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIRecipientsInner>;
    /**
    * Object Array representation of transaction senders
    */
    'senders': Array<ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRISendersInner>;
    /**
    * Numeric representation of the transaction size
    */
    'size': number;
    /**
    * Numeric representation of the timestamp in seconds since epoch
    */
    'timestamp': number;
    /**
    * Numeric representation of the transaction version
    */
    'version': number;
    'minedInBlock': ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIMinedInBlock;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIFee"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "Array<ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIInputsInner>"
        },
        {
            "name": "locktime",
            "baseName": "locktime",
            "type": "number"
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "Array<ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIOutputsInner>"
        },
        {
            "name": "positionInBlock",
            "baseName": "positionInBlock",
            "type": "number"
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIRecipientsInner>"
        },
        {
            "name": "senders",
            "baseName": "senders",
            "type": "Array<ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRISendersInner>"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "minedInBlock",
            "baseName": "minedInBlock",
            "type": "ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIMinedInBlock"
        }    ];

    static getAttributeTypeMap() {
        return ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRI.attributeTypeMap;
    }
}

