/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIMinedInBlock } from './listConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIMinedInBlock';
import { ListConfirmedTransactionsByAddressUTXOHistoricalRIBSZ } from './listConfirmedTransactionsByAddressUTXOHistoricalRIBSZ';
import { ListConfirmedTransactionsByAddressUTXOHistoricalRIBlockchaiSpecific } from './listConfirmedTransactionsByAddressUTXOHistoricalRIBlockchaiSpecific';
import { ListConfirmedTransactionsByAddressUTXOHistoricalRIFee } from './listConfirmedTransactionsByAddressUTXOHistoricalRIFee';
import { ListConfirmedTransactionsByAddressUTXOHistoricalRIInputsInner } from './listConfirmedTransactionsByAddressUTXOHistoricalRIInputsInner';
import { ListConfirmedTransactionsByAddressUTXOHistoricalRIOutputsInner } from './listConfirmedTransactionsByAddressUTXOHistoricalRIOutputsInner';
import { ListConfirmedTransactionsByAddressUTXOHistoricalRIRecipientsInner } from './listConfirmedTransactionsByAddressUTXOHistoricalRIRecipientsInner';
import { ListConfirmedTransactionsByAddressUTXOHistoricalRISendersInner } from './listConfirmedTransactionsByAddressUTXOHistoricalRISendersInner';

export class ListConfirmedTransactionsByAddressUTXOHistoricalRI {
    'fee': ListConfirmedTransactionsByAddressUTXOHistoricalRIFee;
    /**
    * String representation of the transaction hash
    */
    'hash': string;
    /**
    * String representation of the transaction identifier (txid)
    */
    'id': string;
    /**
    * Numeric representation of the transaction locktime
    */
    'locktime': number;
    /**
    * Numeric representation of the index
    */
    'positionInBlock': number;
    /**
    * Numeric representation of the transaction size
    */
    'size': number;
    /**
    * Numeric representation of the timestamp in seconds since epoch
    */
    'timestamp': number;
    /**
    * Numeric representation of the transaction version
    */
    'version': number;
    'minedInBlock': ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIMinedInBlock;
    /**
    * Object Array representation of transaction inputs
    */
    'inputs': Array<ListConfirmedTransactionsByAddressUTXOHistoricalRIInputsInner>;
    /**
    * Object Array representation of transaction outputs
    */
    'outputs': Array<ListConfirmedTransactionsByAddressUTXOHistoricalRIOutputsInner>;
    /**
    * Object Array representation of transaction receivers
    */
    'recipients': Array<ListConfirmedTransactionsByAddressUTXOHistoricalRIRecipientsInner>;
    /**
    * Object Array representation of transaction senders
    */
    'senders': Array<ListConfirmedTransactionsByAddressUTXOHistoricalRISendersInner>;
    'blockchaiSpecific': ListConfirmedTransactionsByAddressUTXOHistoricalRIBlockchaiSpecific;
    'blockchainSpecific'?: ListConfirmedTransactionsByAddressUTXOHistoricalRIBSZ;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListConfirmedTransactionsByAddressUTXOHistoricalRIFee"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "locktime",
            "baseName": "locktime",
            "type": "number"
        },
        {
            "name": "positionInBlock",
            "baseName": "positionInBlock",
            "type": "number"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "minedInBlock",
            "baseName": "minedInBlock",
            "type": "ListConfirmedTransactionsByAddressByTimestampUTXOHistoricalRIMinedInBlock"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "Array<ListConfirmedTransactionsByAddressUTXOHistoricalRIInputsInner>"
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "Array<ListConfirmedTransactionsByAddressUTXOHistoricalRIOutputsInner>"
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<ListConfirmedTransactionsByAddressUTXOHistoricalRIRecipientsInner>"
        },
        {
            "name": "senders",
            "baseName": "senders",
            "type": "Array<ListConfirmedTransactionsByAddressUTXOHistoricalRISendersInner>"
        },
        {
            "name": "blockchaiSpecific",
            "baseName": "blockchaiSpecific",
            "type": "ListConfirmedTransactionsByAddressUTXOHistoricalRIBlockchaiSpecific"
        },
        {
            "name": "blockchainSpecific",
            "baseName": "blockchainSpecific",
            "type": "ListConfirmedTransactionsByAddressUTXOHistoricalRIBSZ"
        }    ];

    static getAttributeTypeMap() {
        return ListConfirmedTransactionsByAddressUTXOHistoricalRI.attributeTypeMap;
    }
}

