/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ListTransactionsByAddressSolanaRINativeBalanceChangesInner {
    /**
    * String representation of the balance change address
    */
    'address': string;
    /**
    * String representation of the balance change after the transaction
    */
    'after': string;
    /**
    * String representation of the balance change before the transaction
    */
    'before': string;
    /**
    * String representation of the balance change calculated
    */
    'change': string;
    /**
    * String representation of the balance change type
    */
    'type'?: ListTransactionsByAddressSolanaRINativeBalanceChangesInner.TypeEnum;
    /**
    * String representation of the balance change unit (ex. SOL)
    */
    'unit': ListTransactionsByAddressSolanaRINativeBalanceChangesInner.UnitEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "after",
            "baseName": "after",
            "type": "string"
        },
        {
            "name": "before",
            "baseName": "before",
            "type": "string"
        },
        {
            "name": "change",
            "baseName": "change",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ListTransactionsByAddressSolanaRINativeBalanceChangesInner.TypeEnum"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "ListTransactionsByAddressSolanaRINativeBalanceChangesInner.UnitEnum"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactionsByAddressSolanaRINativeBalanceChangesInner.attributeTypeMap;
    }
}

export namespace ListTransactionsByAddressSolanaRINativeBalanceChangesInner {
    export enum TypeEnum {
        Native = <any> 'native'
    }
    export enum UnitEnum {
        Sol = <any> 'SOL'
    }
}
