/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListTokensTransfersByTransactionHashEVMRIFee } from './listTokensTransfersByTransactionHashEVMRIFee';
import { ListTokensTransfersByTransactionHashEVMRITokenData } from './listTokensTransfersByTransactionHashEVMRITokenData';

export class ListTokensTransfersByTransactionHashEVMRI {
    /**
    * Defines the address to which the recipient receives the transferred tokens.
    */
    'recipient': string;
    /**
    * Defines the address from which the sender transfers tokens.
    */
    'sender': string;
    'tokenData': ListTokensTransfersByTransactionHashEVMRITokenData;
    'fee': ListTokensTransfersByTransactionHashEVMRIFee;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "string"
        },
        {
            "name": "tokenData",
            "baseName": "tokenData",
            "type": "ListTokensTransfersByTransactionHashEVMRITokenData"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListTokensTransfersByTransactionHashEVMRIFee"
        }    ];

    static getAttributeTypeMap() {
        return ListTokensTransfersByTransactionHashEVMRI.attributeTypeMap;
    }
}

