/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListSyncedHDWalletsXPubYPubZPubRI } from './listSyncedHDWalletsXPubYPubZPubRI';

export class ListSyncedHDWalletsXPubYPubZPubRData {
    /**
    * Defines how many items should be returned in the response per page basis.
    */
    'limit': number;
    /**
    * The starting index of the response items, i.e. where the response should start listing the returned items.
    */
    'offset': number;
    /**
    * Defines the total number of items returned in the response.
    */
    'total': number;
    'items': Array<ListSyncedHDWalletsXPubYPubZPubRI>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ListSyncedHDWalletsXPubYPubZPubRI>"
        }    ];

    static getAttributeTypeMap() {
        return ListSyncedHDWalletsXPubYPubZPubRData.attributeTypeMap;
    }
}

