/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListTransactionsByBlockHashUTXOsRIBSZ } from './listTransactionsByBlockHashUTXOsRIBSZ';
import { ListTransactionsByBlockHashUTXOsRIFee } from './listTransactionsByBlockHashUTXOsRIFee';
import { ListTransactionsByBlockHashUTXOsRIInputsInner } from './listTransactionsByBlockHashUTXOsRIInputsInner';
import { ListTransactionsByBlockHashUTXOsRIOutputsInner } from './listTransactionsByBlockHashUTXOsRIOutputsInner';
import { ListTransactionsByBlockHashUTXOsRIRecipientsInner } from './listTransactionsByBlockHashUTXOsRIRecipientsInner';
import { ListTransactionsByBlockHashUTXOsRISendersInner } from './listTransactionsByBlockHashUTXOsRISendersInner';

export class ListTransactionsByBlockHashUTXOsRI {
    /**
    * Represents the unique identifier of a transaction, i.e. it could be `transactionId` in UTXO-based protocols like Bitcoin, and transaction `hash` in Ethereum blockchain.
    */
    'id': string;
    /**
    * Represents the time at which a particular transaction can be added to the blockchain.
    */
    'locktime': number;
    /**
    * Represents the total size of this transaction.
    */
    'size': number;
    /**
    * Numeric representation of the transaction Represents the transaction version number.
    */
    'version': number;
    'fee': ListTransactionsByBlockHashUTXOsRIFee;
    /**
    * Represents the same as `transactionId` for account-based protocols like Ethereum, while it could be different in UTXO-based protocols like Bitcoin. E.g., in UTXO-based protocols `hash` is different from `transactionId` for SegWit transactions.
    */
    'hash': string;
    /**
    * Object Array representation of transaction inputs
    */
    'inputs': Array<ListTransactionsByBlockHashUTXOsRIInputsInner>;
    /**
    * Object Array representation of transaction outputs
    */
    'outputs': Array<ListTransactionsByBlockHashUTXOsRIOutputsInner>;
    /**
    * Represents the index position of the transaction in the specific block.
    */
    'positionInBlock': number;
    /**
    * Represents a list of recipient addresses with the respective amounts. In account-based protocols like Ethereum there is only one address in this list.
    */
    'recipients': Array<ListTransactionsByBlockHashUTXOsRIRecipientsInner>;
    /**
    * Represents a list of sender addresses with the respective amounts. In account-based protocols like Ethereum there is only one address in this list.
    */
    'senders': Array<ListTransactionsByBlockHashUTXOsRISendersInner>;
    'blockchainSpecific'?: ListTransactionsByBlockHashUTXOsRIBSZ;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "locktime",
            "baseName": "locktime",
            "type": "number"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListTransactionsByBlockHashUTXOsRIFee"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "Array<ListTransactionsByBlockHashUTXOsRIInputsInner>"
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "Array<ListTransactionsByBlockHashUTXOsRIOutputsInner>"
        },
        {
            "name": "positionInBlock",
            "baseName": "positionInBlock",
            "type": "number"
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<ListTransactionsByBlockHashUTXOsRIRecipientsInner>"
        },
        {
            "name": "senders",
            "baseName": "senders",
            "type": "Array<ListTransactionsByBlockHashUTXOsRISendersInner>"
        },
        {
            "name": "blockchainSpecific",
            "baseName": "blockchainSpecific",
            "type": "ListTransactionsByBlockHashUTXOsRIBSZ"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactionsByBlockHashUTXOsRI.attributeTypeMap;
    }
}

