/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListConfirmedTransactionsByAddressUTXOsRIBSZValueBalance } from './listConfirmedTransactionsByAddressUTXOsRIBSZValueBalance';

/**
* Zcash
*/
export class ListConfirmedTransactionsByAddressUTXOsRIBSZ {
    /**
    * Numeric representation of the transaction block height expiration
    */
    'expiryHeight': number;
    'overwintered': boolean;
    'valueBalance': ListConfirmedTransactionsByAddressUTXOsRIBSZValueBalance;
    /**
    * String representation of the transaction version group id
    */
    'versionGroupId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiryHeight",
            "baseName": "expiryHeight",
            "type": "number"
        },
        {
            "name": "overwintered",
            "baseName": "overwintered",
            "type": "boolean"
        },
        {
            "name": "valueBalance",
            "baseName": "valueBalance",
            "type": "ListConfirmedTransactionsByAddressUTXOsRIBSZValueBalance"
        },
        {
            "name": "versionGroupId",
            "baseName": "versionGroupId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListConfirmedTransactionsByAddressUTXOsRIBSZ.attributeTypeMap;
    }
}

