/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListHDWalletXPubYPubZPubTransactionsUTXORIRecipientsInnerValue } from './listHDWalletXPubYPubZPubTransactionsUTXORIRecipientsInnerValue';

export class ListHDWalletXPubYPubZPubTransactionsUTXORIRecipientsInner {
    /**
    * The address which receives this transaction. In UTXO-based protocols like Bitcoin there could be several senders while in account-based protocols like Ethereum there is always only one recipient.
    */
    'address': string;
    /**
    * Defines whether an address is a child address derived from the HD wallet (xPub, yPub, zPub) as boolean.
    */
    'isMember': boolean;
    'value': ListHDWalletXPubYPubZPubTransactionsUTXORIRecipientsInnerValue;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "isMember",
            "baseName": "isMember",
            "type": "boolean"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ListHDWalletXPubYPubZPubTransactionsUTXORIRecipientsInnerValue"
        }    ];

    static getAttributeTypeMap() {
        return ListHDWalletXPubYPubZPubTransactionsUTXORIRecipientsInner.attributeTypeMap;
    }
}

