/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListTransactionsByBlockHeightXRPRIFee } from './listTransactionsByBlockHeightXRPRIFee';
import { ListTransactionsByBlockHeightXRPRIOffer } from './listTransactionsByBlockHeightXRPRIOffer';
import { ListTransactionsByBlockHeightXRPRIReceive } from './listTransactionsByBlockHeightXRPRIReceive';
import { ListTransactionsByBlockHeightXRPRIValue } from './listTransactionsByBlockHeightXRPRIValue';

export class ListTransactionsByBlockHeightXRPRI {
    'additionalData'?: string;
    /**
    * Defines a specific Tag that is an additional XRP address feature. It helps identifying a transaction recipient beyond a wallet address.
    */
    'destinationTag'?: number;
    'hash': string;
    'positionInBlock': number;
    /**
    * String representation of the transaction to address
    */
    'recipient': string;
    /**
    * String representation of the transaction from address
    */
    'sender': string;
    'status': string;
    /**
    * Defines the exact date/time in Unix Timestamp when this transaction was mined, confirmed or first seen in Mempool, if it is unconfirmed.
    */
    'timestamp': number;
    'type': string;
    'fee': ListTransactionsByBlockHeightXRPRIFee;
    'offer': ListTransactionsByBlockHeightXRPRIOffer;
    'receive': ListTransactionsByBlockHeightXRPRIReceive;
    'value': ListTransactionsByBlockHeightXRPRIValue;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additionalData",
            "baseName": "additionalData",
            "type": "string"
        },
        {
            "name": "destinationTag",
            "baseName": "destinationTag",
            "type": "number"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "positionInBlock",
            "baseName": "positionInBlock",
            "type": "number"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListTransactionsByBlockHeightXRPRIFee"
        },
        {
            "name": "offer",
            "baseName": "offer",
            "type": "ListTransactionsByBlockHeightXRPRIOffer"
        },
        {
            "name": "receive",
            "baseName": "receive",
            "type": "ListTransactionsByBlockHeightXRPRIReceive"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ListTransactionsByBlockHeightXRPRIValue"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactionsByBlockHeightXRPRI.attributeTypeMap;
    }
}

