/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListHDWalletXPubYPubZPubTransactionsEVMRIMinedInBlock } from './listHDWalletXPubYPubZPubTransactionsEVMRIMinedInBlock';
import { ListHDWalletXPubYPubZPubTransactionsEVMRIRecipientInner } from './listHDWalletXPubYPubZPubTransactionsEVMRIRecipientInner';
import { ListHDWalletXPubYPubZPubTransactionsEVMRISenderInner } from './listHDWalletXPubYPubZPubTransactionsEVMRISenderInner';
import { ListHDWalletXPubYPubZPubTransactionsUTXORIFee } from './listHDWalletXPubYPubZPubTransactionsUTXORIFee';

export class ListHDWalletXPubYPubZPubTransactionsEVMRI {
    /**
    * Represents the same as `transactionId` for account-based protocols like Ethereum, while it could be different in UTXO-based protocols like Bitcoin. E.g., in UTXO-based protocols `hash` is different from `transactionId` for SegWit transactions.
    */
    'hash': string;
    /**
    * Represents the index position of the transaction in the block.
    */
    'positionInBlock': number;
    /**
    * Represents a list of recipient addresses with the respective amounts. In account-based protocols like Ethereum there is only one address in this list.
    */
    'recipient': Array<ListHDWalletXPubYPubZPubTransactionsEVMRIRecipientInner>;
    /**
    * Represents a list of sender addresses with the respective amounts. In account-based protocols like Ethereum there is only one address in this list.
    */
    'sender': Array<ListHDWalletXPubYPubZPubTransactionsEVMRISenderInner>;
    /**
    * Defines the exact date/time in Unix Timestamp when this transaction was mined, confirmed or first seen in Mempool, if it is unconfirmed.
    */
    'timestamp': number;
    'fee': ListHDWalletXPubYPubZPubTransactionsUTXORIFee;
    'minedInBlock': ListHDWalletXPubYPubZPubTransactionsEVMRIMinedInBlock;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "positionInBlock",
            "baseName": "positionInBlock",
            "type": "number"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "Array<ListHDWalletXPubYPubZPubTransactionsEVMRIRecipientInner>"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "Array<ListHDWalletXPubYPubZPubTransactionsEVMRISenderInner>"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListHDWalletXPubYPubZPubTransactionsUTXORIFee"
        },
        {
            "name": "minedInBlock",
            "baseName": "minedInBlock",
            "type": "ListHDWalletXPubYPubZPubTransactionsEVMRIMinedInBlock"
        }    ];

    static getAttributeTypeMap() {
        return ListHDWalletXPubYPubZPubTransactionsEVMRI.attributeTypeMap;
    }
}

