/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListConfirmedTokensTransfersByAddressEVMRI } from './listConfirmedTokensTransfersByAddressEVMRI';

export class ListConfirmedTokensTransfersByAddressEVMRData {
    /**
    * Defines how many items should be returned in the response per page basis.
    */
    'limit': number;
    /**
    * Defines the id of the previous listed record id from which the current list should start from.
    */
    'startingAfter'?: string;
    /**
    * Defines whether or not there are more elements available after this set.
    */
    'hasMore': boolean;
    /**
    * Defines the id of the next page which the next list should start from.
    */
    'nextStartingAfter'?: string;
    /**
    * Defines what the sorting order is either ascending or descending.
    */
    'sortingOrder'?: string;
    'items': Array<ListConfirmedTokensTransfersByAddressEVMRI>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "startingAfter",
            "baseName": "startingAfter",
            "type": "string"
        },
        {
            "name": "hasMore",
            "baseName": "hasMore",
            "type": "boolean"
        },
        {
            "name": "nextStartingAfter",
            "baseName": "nextStartingAfter",
            "type": "string"
        },
        {
            "name": "sortingOrder",
            "baseName": "sortingOrder",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ListConfirmedTokensTransfersByAddressEVMRI>"
        }    ];

    static getAttributeTypeMap() {
        return ListConfirmedTokensTransfersByAddressEVMRData.attributeTypeMap;
    }
}

