/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListTransactionsByBlockHashEVMRIBlockchainSpecific } from './listTransactionsByBlockHashEVMRIBlockchainSpecific';
import { ListTransactionsByBlockHashEVMRIFee } from './listTransactionsByBlockHashEVMRIFee';
import { ListTransactionsByBlockHashEVMRIGasPrice } from './listTransactionsByBlockHashEVMRIGasPrice';
import { ListTransactionsByBlockHashEVMRIValue } from './listTransactionsByBlockHashEVMRIValue';

export class ListTransactionsByBlockHashEVMRI {
    /**
    * Numeric representation of the transaction contract
    */
    'contract': number;
    'fee': ListTransactionsByBlockHashEVMRIFee;
    /**
    * String representation of the transaction hash
    */
    'hash': string;
    /**
    * Numeric representation of the transaction input
    */
    'inputData': number;
    /**
    * Represents the index position of the transaction in the specific block.
    */
    'positionInBlock': number;
    /**
    * String representation of the transaction to address
    */
    'recipient': string;
    /**
    * String representation of the transaction from address
    */
    'sender': string;
    /**
    * String representation of the transaction status
    */
    'status': string;
    /**
    * Defines the exact date/time in Unix Timestamp when this transaction was mined, confirmed or first seen in Mempool, if it is unconfirmed.
    */
    'timestamp': number;
    'value': ListTransactionsByBlockHashEVMRIValue;
    /**
    * String representation of the transaction gas
    */
    'gasLimit': number;
    /**
    * Numeric representation of the transaction gas used
    */
    'gasUsed': number;
    'gasPrice': ListTransactionsByBlockHashEVMRIGasPrice;
    'blockchainSpecific': ListTransactionsByBlockHashEVMRIBlockchainSpecific;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contract",
            "baseName": "contract",
            "type": "number"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListTransactionsByBlockHashEVMRIFee"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "inputData",
            "baseName": "inputData",
            "type": "number"
        },
        {
            "name": "positionInBlock",
            "baseName": "positionInBlock",
            "type": "number"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ListTransactionsByBlockHashEVMRIValue"
        },
        {
            "name": "gasLimit",
            "baseName": "gasLimit",
            "type": "number"
        },
        {
            "name": "gasUsed",
            "baseName": "gasUsed",
            "type": "number"
        },
        {
            "name": "gasPrice",
            "baseName": "gasPrice",
            "type": "ListTransactionsByBlockHashEVMRIGasPrice"
        },
        {
            "name": "blockchainSpecific",
            "baseName": "blockchainSpecific",
            "type": "ListTransactionsByBlockHashEVMRIBlockchainSpecific"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactionsByBlockHashEVMRI.attributeTypeMap;
    }
}

