/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetTransactionDetailsByTransactionHashUTXOsRIInputsInnerValue } from './getTransactionDetailsByTransactionHashUTXOsRIInputsInnerValue';
import { ListConfirmedTransactionsByAddressUTXOsRIOutputsInnerScript } from './listConfirmedTransactionsByAddressUTXOsRIOutputsInnerScript';

export class ListTransactionsByBlockHeightUTXOsRIOutputsInner {
    'addresses'?: Array<string>;
    /**
    * Boolean representation of is the transaction output spent
    */
    'isSpent': boolean;
    'script': ListConfirmedTransactionsByAddressUTXOsRIOutputsInnerScript;
    'value'?: GetTransactionDetailsByTransactionHashUTXOsRIInputsInnerValue;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<string>"
        },
        {
            "name": "isSpent",
            "baseName": "isSpent",
            "type": "boolean"
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "ListConfirmedTransactionsByAddressUTXOsRIOutputsInnerScript"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "GetTransactionDetailsByTransactionHashUTXOsRIInputsInnerValue"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactionsByBlockHeightUTXOsRIOutputsInner.attributeTypeMap;
    }
}

