/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListTransactionsByBlockHeightEVMRIBlockchainSpecific } from './listTransactionsByBlockHeightEVMRIBlockchainSpecific';
import { ListTransactionsByBlockHeightEVMRIFee } from './listTransactionsByBlockHeightEVMRIFee';
import { ListTransactionsByBlockHeightEVMRIGasPrice } from './listTransactionsByBlockHeightEVMRIGasPrice';
import { ListTransactionsByBlockHeightEVMRIValue } from './listTransactionsByBlockHeightEVMRIValue';

export class ListTransactionsByBlockHeightEVMRI {
    /**
    * Numeric representation of the transaction contract
    */
    'contract': string;
    'fee': ListTransactionsByBlockHeightEVMRIFee;
    /**
    * String representation of the transaction hash
    */
    'hash': string;
    /**
    * Numeric representation of the transaction input
    */
    'inputData': string;
    /**
    * Numeric representation of the transaction index
    */
    'positionInBlock': number;
    /**
    * String representation of the transaction to address
    */
    'recipient': string;
    /**
    * String representation of the transaction from address
    */
    'sender': string;
    /**
    * String representation of the transaction status
    */
    'status': string;
    /**
    * Numeric representation of the timestamp in seconds since epoch
    */
    'timestamp': number;
    'value': ListTransactionsByBlockHeightEVMRIValue;
    /**
    * String representation of the transaction gas
    */
    'gasLimit': number;
    /**
    * Numeric representation of the transaction gas used
    */
    'gasUsed': number;
    'gasPrice': ListTransactionsByBlockHeightEVMRIGasPrice;
    'blockchainSpecific': ListTransactionsByBlockHeightEVMRIBlockchainSpecific;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contract",
            "baseName": "contract",
            "type": "string"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "ListTransactionsByBlockHeightEVMRIFee"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "inputData",
            "baseName": "inputData",
            "type": "string"
        },
        {
            "name": "positionInBlock",
            "baseName": "positionInBlock",
            "type": "number"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "ListTransactionsByBlockHeightEVMRIValue"
        },
        {
            "name": "gasLimit",
            "baseName": "gasLimit",
            "type": "number"
        },
        {
            "name": "gasUsed",
            "baseName": "gasUsed",
            "type": "number"
        },
        {
            "name": "gasPrice",
            "baseName": "gasPrice",
            "type": "ListTransactionsByBlockHeightEVMRIGasPrice"
        },
        {
            "name": "blockchainSpecific",
            "baseName": "blockchainSpecific",
            "type": "ListTransactionsByBlockHeightEVMRIBlockchainSpecific"
        }    ];

    static getAttributeTypeMap() {
        return ListTransactionsByBlockHeightEVMRI.attributeTypeMap;
    }
}

