/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItemFee } from './prepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItemFee';

export class PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItem {
    /**
    * Representation of the additional data.
    */
    'additionalData'?: string;
    /**
    * Representation of the amount of the transaction
    */
    'amount': string;
    /**
    * Representation of the nonce value
    */
    'nonce'?: string;
    /**
    * Represents a list of recipient addresses with the respective amounts. In account-based protocols like Ethereum there is only one address in this list.
    */
    'recipient': string;
    /**
    * Represents a  sender address with the respective amount. In account-based protocols like Ethereum there is only one address in this list.
    */
    'sender': string;
    'fee': PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItemFee;
    /**
    * Representation of the transaction type
    */
    'transactionType'?: PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItem.TransactionTypeEnum = PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItem.TransactionTypeEnum.GasFeeMarketTransaction;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additionalData",
            "baseName": "additionalData",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "string"
        },
        {
            "name": "recipient",
            "baseName": "recipient",
            "type": "string"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "string"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItemFee"
        },
        {
            "name": "transactionType",
            "baseName": "transactionType",
            "type": "PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItem.TransactionTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItem.attributeTypeMap;
    }
}

export namespace PrepareATransactionFromAnAddressInHDWalletXPubYPubZPubEVMRBDataItem {
    export enum TransactionTypeEnum {
        LegacyTransaction = <any> 'legacy-transaction',
        AccessListTransaction = <any> 'access-list-transaction',
        GasFeeMarketTransaction = <any> 'gas-fee-market-transaction'
    }
}
