/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Defines the amount of the transaction fee.
*/
export class PrepareAFungibleTokenTransferFromAddressEVMRIFee {
    /**
    * Represents the price offered to the miner to purchase this amount of gas.
    */
    'gasPrice': number;
    /**
    * Representation of the max fee per gas value
    */
    'maxFeePerGas': number;
    /**
    * Representation of the max priority fee per gas value
    */
    'maxPriorityFeePerGas': number;
    'unit': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gasPrice",
            "baseName": "gasPrice",
            "type": "number"
        },
        {
            "name": "maxFeePerGas",
            "baseName": "maxFeePerGas",
            "type": "number"
        },
        {
            "name": "maxPriorityFeePerGas",
            "baseName": "maxPriorityFeePerGas",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PrepareAFungibleTokenTransferFromAddressEVMRIFee.attributeTypeMap;
    }
}

