/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee } from './prepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee';
import { PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemRecipientsInner } from './prepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemRecipientsInner';

export class PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItem {
    /**
    * Representation of the additional data.
    */
    'additionalData'?: string;
    /**
    * Represents the time at which a particular transaction can be added to the blockchain.
    */
    'locktime'?: number;
    'fee': PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee;
    /**
    * Representation of the transaction\'s strategy type
    */
    'prepareStrategy'?: PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItem.PrepareStrategyEnum;
    /**
    * Object Array representation of transaction receivers
    */
    'recipients': Array<PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemRecipientsInner>;
    /**
    * Representation of whether the transaction is replaceable. This is an Optional attribute that is not supported for Dogecoin, Dash and Bitcoin-Cash.
    */
    'replaceable'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additionalData",
            "baseName": "additionalData",
            "type": "string"
        },
        {
            "name": "locktime",
            "baseName": "locktime",
            "type": "number"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee"
        },
        {
            "name": "prepareStrategy",
            "baseName": "prepareStrategy",
            "type": "PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItem.PrepareStrategyEnum"
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemRecipientsInner>"
        },
        {
            "name": "replaceable",
            "baseName": "replaceable",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItem.attributeTypeMap;
    }
}

export namespace PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItem {
    export enum PrepareStrategyEnum {
        None = <any> 'none',
        MinimizeDust = <any> 'minimize-dust',
        OptimizeSize = <any> 'optimize-size'
    }
}
