/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Defines the amount of the transaction fee.
*/
export class PrepareAFungibleTokenTransferFromAddressEVMRBDataItemFee {
    /**
    * Representation of the exact amount to be transfered.
    */
    'exactAmount': string;
    /**
    * Represents the fee priority of the automation, whether it is \"slow\", \"standard\" or \"fast\".
    */
    'priority': PrepareAFungibleTokenTransferFromAddressEVMRBDataItemFee.PriorityEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "exactAmount",
            "baseName": "exactAmount",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "PrepareAFungibleTokenTransferFromAddressEVMRBDataItemFee.PriorityEnum"
        }    ];

    static getAttributeTypeMap() {
        return PrepareAFungibleTokenTransferFromAddressEVMRBDataItemFee.attributeTypeMap;
    }
}

export namespace PrepareAFungibleTokenTransferFromAddressEVMRBDataItemFee {
    export enum PriorityEnum {
        Slow = <any> 'slow',
        Standard = <any> 'standard',
        Fast = <any> 'fast'
    }
}
