/**
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2024-12-12
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* When isConfirmed is True - Defines the amount of the transaction fee When isConfirmed is False - For ETH-based blockchains this attribute represents the max fee value.
*/
export class PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee {
    /**
    * Representation of the address
    */
    'address'?: string;
    /**
    * Representation of the exact amount
    */
    'exactAmount'?: string;
    /**
    * Representation of the fee priority
    */
    'priority'?: PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee.PriorityEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "exactAmount",
            "baseName": "exactAmount",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee.PriorityEnum"
        }    ];

    static getAttributeTypeMap() {
        return PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee.attributeTypeMap;
    }
}

export namespace PrepareAUTXOBasedTransactionFromHDWalletXPubYPubZPubRBDataItemFee {
    export enum PriorityEnum {
        Slow = <any> 'slow',
        Standard = <any> 'standard',
        Fast = <any> 'fast'
    }
}
